### ISSUE TITLE
NPE without any class with @Api annotation

### ISSUE THREAD

**Issue by m-radzikowski** [swagger-api/swagger-core#1000]
If there is no class with `@Api` annotation trying to get `swagger.json` causes NPE. This may be very confusing at the beginning, when we are implementing Swagger step-by-step and get exception.

Stack:
```
java.lang.NullPointerException
	at com.wordnik.swagger.jaxrs.config.BeanConfig.configure(BeanConfig.java:196)
	at com.wordnik.swagger.jaxrs.listing.ApiListingResource.scan(ApiListingResource.java:52)
	at com.wordnik.swagger.jaxrs.listing.ApiListingResource.getListingJson(ApiListingResource.java:79)
	...
```
So we have to check for nulls somewhere in this area: https://github.com/swagger-api/swagger-core/blob/c4260bea041027f9887c67d5d6c6eb408c238969/modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/config/BeanConfig.java#L197

**Comment by m-radzikowski** [comment]
Log above was from `swagger-jersey2-jaxrs` `1.5.3-M1`. On `1.5.0-M2` and `1.5.1-M2` log is:
```
java.lang.NullPointerException
	at com.wordnik.swagger.jaxrs.config.BeanConfig.configure(BeanConfig.java:210)
	at com.wordnik.swagger.jaxrs.listing.ApiListingResource.scan(ApiListingResource.java:52)
	at com.wordnik.swagger.jaxrs.listing.ApiListingResource.getListingJson(ApiListingResource.java:79)
	...
```
and it may be related to #963

**Comment by webron** [comment]
Fixed in develop_2.0.
