### ISSUE TITLE
com.wordnik.swagger.jaxrs.utils.ParameterUtils does not support Nested ParameterizedTypes

### ISSUE THREAD

**Issue by bakito** [swagger-api/swagger-core#1061]
If I user nested ParameterizedTypes (E.g RequestEntity<Pageable<Unqualified, PartnerPublicFilter>> query) in the ApiOperation method I get the following exception:

[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.0.0:generate (default-cli) on project pass-mepo-server: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.0.0:generate (default-cli) on project pass-mepo-server: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
        at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:91)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
        at com.wordnik.swagger.jaxrs.utils.ParameterUtils.isMethodArgumentAnArray(ParameterUtils.java:43)
        at com.github.kongchen.swagger.docgen.reader.AbstractReader.getParameters(AbstractReader.java:275)
        at com.github.kongchen.swagger.docgen.reader.JaxrsReader.parseMethod(JaxrsReader.java:345)
        at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:106)
        at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:66)
        at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:57)
        at com.github.kongchen.swagger.docgen.mavenplugin.MavenDocumentSource.loadDocuments(MavenDocumentSource.java:40)
        at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:69)
        ... 21 more

**Comment by bakito** [comment]
I'm not familiar with the Scala Test framework that is used, so I wrote a JUnit test to show the problem:

package com.wordnik.swagger.jaxrs.utils;

import java.lang.reflect.Method;

import org.junit.Test;

public class ParameterUtilsTest {
	@Test
	public void test_simple_parameterized_type() throws NoSuchMethodException, SecurityException {
		Method method = this.getClass().getMethod("testMethod1", MyType.class);
		ParameterUtils.isMethodArgumentAnArray(method.getParameterTypes()[0], method.getGenericParameterTypes()[0]);
	}

	@Test
	public void test_nested_parameterized_types() throws NoSuchMethodException, SecurityException {
		Method method = this.getClass().getMethod("testMethod2", MyType.class);
		ParameterUtils.isMethodArgumentAnArray(method.getParameterTypes()[0], method.getGenericParameterTypes()[0]);
	}

	public void testMethod1(MyType<String> type) {
	}

	public void testMethod2(MyType<MyType<String>> type) {
	}

	private class MyType<T> {
	}
}

**Comment by webron** [comment]
Fixed in develop_2.0.
