### ISSUE TITLE
Petstore deserialization fails due to default value type

### ISSUE THREAD

**Issue by quilicicf** [swagger-api/swagger-core#1112]
Hi, 

Trying to deserialize the [petstore](http://petstore.swagger.io/v2/swagger.json) in Java, I encountered a JsonMappingException. 

Working on tag [v1.5.3-M1](https://github.com/swagger-api/swagger-core/tree/v1.5.3-M1) with the following code: 

```java
Swagger swagger;
String url = "http://petstore.swagger.io/v2/swagger.json";
try {
    ClientResource cr = new ClientResource(url);
    Representation result = cr.get();
    String resultAsText = result.getText();
    swagger = Json.mapper().readValue(resultAsText, Swagger.class);
    ...
} catch (Exception e) {
    e.printStackTrace();
}
```

My understanding is that for any sub-type of `AbstractProperty`, the type of field `default` is String although this is not the case in the JSON provided which is Swagger 2.0 compliant.

The exception: 

```
com.fasterxml.jackson.databind.JsonMappingException: com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: com.wordnik.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["complete"]) (through reference chain: com.wordnik.swagger.models.Swagger["definitions"]->java.util.LinkedHashMap["Order"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.wrapAndThrow(MapDeserializer.java:566)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:472)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:320)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:238)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2161)
	at org.restlet.test.ext.apispark.conversion.swagger.v2_0.SwaggerLoader.readJsonString(SwaggerLoader.java:44)
	at fr.quilici.swagger.two.conversion.TestImportSwagger2.readFromUrl(TestImportSwagger2.java:47)
	at fr.quilici.swagger.two.conversion.TestImportSwagger2.main(TestImportSwagger2.java:34)
Caused by: java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: com.wordnik.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["complete"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:2774)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:2700)
	at com.wordnik.swagger.util.ModelDeserializer.deserialize(ModelDeserializer.java:55)
	at com.wordnik.swagger.util.ModelDeserializer.deserialize(ModelDeserializer.java:16)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:460)
	... 11 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: com.wordnik.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["complete"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.wrapAndThrow(MapDeserializer.java:566)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:472)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:320)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:238)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:2769)
	... 15 more
Caused by: java.lang.ClassCastException: com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode
	at com.wordnik.swagger.util.PropertyDeserializer.propertyFromNode(PropertyDeserializer.java:75)
	at com.wordnik.swagger.util.PropertyDeserializer.deserialize(PropertyDeserializer.java:22)
	at com.wordnik.swagger.util.PropertyDeserializer.deserialize(PropertyDeserializer.java:15)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:460)
	... 22 more
```

**Comment by webron** [comment]
Can you try with 1.5.2-M2?

**Comment by webron** [comment]
@quilicicf - any update?

**Comment by quilicicf** [comment]
Hi, sorry for the delay. 

Same issue with version 1.5.2-M2:

```
com.fasterxml.jackson.databind.JsonMappingException: com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: com.wordnik.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["complete"]) (through reference chain: com.wordnik.swagger.models.Swagger["definitions"]->java.util.LinkedHashMap["Order"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.wrapAndThrow(MapDeserializer.java:566)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:472)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:320)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:238)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1269)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:864)
	at org.restlet.ext.jackson.JacksonRepresentation.getObject(JacksonRepresentation.java:309)
	at org.restlet.ext.apispark.internal.conversion.ImportUtils.getAndDeserialize(ImportUtils.java:87)
	... 3 more
Caused by: java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: com.wordnik.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["complete"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:2774)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:2700)
	at com.wordnik.swagger.util.ModelDeserializer.deserialize(ModelDeserializer.java:55)
	at com.wordnik.swagger.util.ModelDeserializer.deserialize(ModelDeserializer.java:16)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:460)
	... 13 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: com.wordnik.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["complete"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.wrapAndThrow(MapDeserializer.java:566)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:472)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:320)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:238)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:2769)
	... 17 more
Caused by: java.lang.ClassCastException: com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode
	at com.wordnik.swagger.util.PropertyDeserializer.propertyFromNode(PropertyDeserializer.java:75)
	at com.wordnik.swagger.util.PropertyDeserializer.deserialize(PropertyDeserializer.java:22)
	at com.wordnik.swagger.util.PropertyDeserializer.deserialize(PropertyDeserializer.java:15)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:460)
	... 24 more
```

**Comment by webron** [comment]
@quilicicf - we just released 1.5.0 - better test with that, even though it'd require code changes.

**Comment by webron** [comment]
@quilicicf - just tested it with 1.5.0 and it seems to work fine. Please upgrade and test. Reopen if needed.

**Comment by quilicicf** [comment]
We switched to 1.5.0. 
Thanks for your help.

**Comment by webron** [comment]
@quilicicf - happy to hear, thanks for the update!
