### ISSUE TITLE
swagger-models does not provides correct MANIFEST entries for OSGI

### ISSUE THREAD

**Issue by rkosegi** [swagger-api/swagger-core#1285]
I'm using swagger-jaxrs with swagger-models and other dependencies with version 1.5.0.
My container is OSGI Karaf.

These are interesting MANIFEST.MF entries of swagger-models:

Export-Package = 
	io.swagger.models.parameters;uses:="com.fasterxml.jackson.annotation,io.swagger.models,io.swagger.models.properties";version=1.5.0,
	io.swagger.models.properties;uses:="com.fasterxml.jackson.annotation,io.swagger.models";version=1.5.0,
	io.swagger.models;uses:="com.fasterxml.jackson.annotation,io.swagger.models.parameters,io.swagger.models.properties,javax.xml.bind.annotation";version=1.5.0

I can't see sub-package named "io.swagger.models.auth", neither OSGI can, which results in runtime NoClassDefFoundError like this:

Caused by: java.lang.NoClassDefFoundError: io/swagger/models/auth/SecuritySchemeDefinition
	at io.swagger.util.Json.create(Json.java:36)[162:my.application.ws:0.0.6.SNAPSHOT]
	at io.swagger.util.Json.mapper(Json.java:23)[162:my.application.ws:0.0.6.SNAPSHOT]
	at io.swagger.converter.ModelConverters.<init>(ModelConverters.java:31)[162:my.application.ws:0.0.6.SNAPSHOT]
	at io.swagger.converter.ModelConverters.<clinit>(ModelConverters.java:23)[162:my.application.ws:0.0.6.SNAPSHOT]
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:768)[162:my.application.ws:0.0.6.SNAPSHOT]
	at io.swagger.jaxrs.Reader.read(Reader.java:286)[162:my.application.ws:0.0.6.SNAPSHOT]
	at io.swagger.jaxrs.Reader.read(Reader.java:169)[162:my.application.ws:0.0.6.SNAPSHOT]
	at io.swagger.jaxrs.Reader.read(Reader.java:146)[162:my.application.ws:0.0.6.SNAPSHOT]

 
 
 Looking at swagger-models POM brings obvious anwser:
 
 https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/pom.xml#L36
 
 Package is not exported.
 
 Why? Did I missed something?

**Comment by webron** [comment]
We're no experts in OSGi. Some other user have mentioned he may submit a few PRs to help the code improve with that regard, but if you know what needs to be done, go ahead and do it.

**Comment by rkosegi** [comment]
Added PR, for me it fixed issue, please review and merge if you think it's ok.

**Comment by webron** [comment]
Fixed in develop_2.0. Thanks!
