### ISSUE TITLE
Use of (sometimes) restricted class sun.reflect.generics.reflectiveObjects

### ISSUE THREAD

**Issue by akbertram** [swagger-api/swagger-core#137]
I'm trying to integrate Swagger into an Guice-Jersey-JAXRS app running on Google AppEngine (phew!)

Everything is almost working, but I'm hitting a security restriction because of a reference to an internal sun.\* class. There's an alternate implementation here http://code.google.com/p/twig-persist/source/browse/src/share/com.vercer.convert/com/vercer/generics/ParameterizedTypeImpl.java?name=v2.0&r=083ff0051f5505e6b8f68e8adcf2fa560beaae92

I will try to submit a pull request but am not yet fluent in scala so if anyone else has a quick fix let me know!

```
    FINE: parsing method getByCode
Feb 20, 2013 9:06:19 PM com.wordnik.swagger.core.SwaggerContext$$anonfun$loadClass$1 apply
FINE: Class not found in classLoader com.google.appengine.tools.development.IsolatedAppClassLoader@37a8fe42
Feb 20, 2013 9:06:19 PM com.wordnik.swagger.core.ApiSpecParserTrait$$anonfun$parseMethod$2 apply
SEVERE: Unable to determine datatype for param 0 in method public org.activityinfo.server.database.hibernate.entity.Country org.activityinfo.server.endpoint.hxl.CountryResource.getByCode(java.lang.String)
java.security.AccessControlException: access denied (java.lang.RuntimePermission accessClassInPackage.sun.reflect.generics.reflectiveObjects)
    at java.security.AccessControlContext.checkPermission(AccessControlContext.java:374)
    at java.security.AccessController.checkPermission(AccessController.java:546)
    at java.lang.SecurityManager.checkPermission(SecurityManager.java:532)
    at com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkPermission(DevAppServerFactory.java:289)
    at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1512)
    at java.lang.ClassLoader$1.run(ClassLoader.java:330)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:328)
    at com.wordnik.swagger.core.ApiPropertiesReader$.getDataType(SpecReader.scala:84)
    at com.wordnik.swagger.core.ApiSpecParserTrait$$anonfun$parseMethod$2.apply(ApiReader.scala:175)
    at com.wordnik.swagger.core.ApiSpecParserTrait$$anonfun$parseMethod$2.apply(ApiReader.scala:168)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
    at scala.collection.mutable.ArrayOps.foreach(ArrayOps.scala:38)
    at com.wordnik.swagger.core.ApiSpecParserTrait$class.parseMethod(ApiReader.scala:168)
    at com.wordnik.swagger.jaxrs.JaxrsApiSpecParser.parseMethod(JaxrsApiReader.scala:73)
    at com.wordnik.swagger.core.ApiSpecParserTrait$$anonfun$parse$1.apply(ApiReader.scala:62)
    at com.wordnik.swagger.core.ApiSpecParserTrait$$anonfun$parse$1.apply(ApiReader.scala:62)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
    at scala.collection.mutable.ArrayOps.foreach(ArrayOps.scala:38)
    at com.wordnik.swagger.core.ApiSpecParserTrait$class.parse(ApiReader.scala:62)
    at com.wordnik.swagger.jaxrs.JaxrsApiSpecParser.parse(JaxrsApiReader.scala:73)
    at com.wordnik.swagger.jaxrs.JaxrsApiReader$.read(JaxrsApiReader.scala:62)
    at com.wordnik.swagger.jaxrs.listing.ApiListing.docForRoute(ApiListing.scala:129)
    at com.wordnik.swagger.jaxrs.listing.ApiListing.apiListing(ApiListing.scala:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
```

**Comment by adcoolguy** [comment]
This is still happening for us. What is the solution again?

**Comment by fehguy** [comment]
Update to 1.5.4
