### ISSUE TITLE
ModelDeserializer can't handle schemas with multiple types

### ISSUE THREAD

**Issue by ePaul** [swagger-api/swagger-core#1401]
(This could be categorized as a bug, or "not yet implemented" needed feature.)

**Summary**
When a schema's `type` property has not a string, but an array, ModelDeserializer.deserialize throws a ClassCastException.

**Reproducible by**

Example schema (bug-trigger.yaml):

```
swagger: '2.0'
info:
  title: Swagger Codegen bug trigger
  description: |
     This demonstrates a bug in swagger-codegen.
  version: 0.0.1
basePath: /api
definitions:
  example:
    type: [ "integer", "null"]
```

Running swagger-codegen:

    java -jar /home/paulo/.m2/repository/io/swagger/swagger-codegen-cli/2.1.4-SNAPSHOT/swagger-codegen-cli-2.1.4-SNAPSHOT.jar generate -i src/main/resources/api/bug-trigger.yaml -l java -o target/generated-sources/swagger-codegen

Output:
```
reading from src/main/resources/api/bug-trigger.yaml
com.fasterxml.jackson.databind.node.ArrayNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: io.swagger.models.Swagger["definitions"]->java.util.LinkedHashMap["example"])
reading from src/main/resources/api/bug-trigger.yaml
com.fasterxml.jackson.databind.node.ArrayNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: io.swagger.models.Swagger["definitions"]->java.util.LinkedHashMap["example"])
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'swagger': was expecting ('true', 'false' or 'null')
 at [Source: src/main/resources/api/bug-trigger.yaml; line: 1, column: 9]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3201)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2360)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:794)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:690)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1861)
        at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:147)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:82)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:36)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:133)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:60)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:134)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

(The exception with the fallback comes from trying to parse it as Swagger 1.* after the original parsing resulted in a ClassCastException – line 55 of ModelDeserializer.java in the 1.5.3 version.)

**Expected behaviour**
The [Spec says for a schema object](http://swagger.io/specification/#schemaObject):

> The following properties are taken directly from the JSON Schema definition and follow the same specifications:  
> [...]
> * type

[JSON Schema validation says in section 5.5.2](http://json-schema.org/latest/json-schema-validation.html#anchor79):

> **5.5.2.  type**
>
> **5.5.2.1.  Valid values**
>
> The value of this keyword MUST be either a string or an array. If it is an array, elements of the array MUST be strings and MUST be unique.
> 
> String values MUST be one of the seven primitive types defined by the core specification.
>
> **5.5.2.2.  Conditions for successful validation**
> 
> An instance matches successfully if its primitive type is one of the types defined by keyword. Recall: "number" includes "integer".

I would interpret this as my `type: ["integer", "null"]` property being valid JSON Schema, and thus also valid Swagger.

I guess the models need to be extended to support such multiple-type properties.

**Comment by webron** [comment]
@ePaul - I'm afraid that's not a valid definition. It probably deserves a clarification in the spec (feel free to open a separate issue on swagger-spec). Swagger does not support multiple types, no matter where. Also, `null` is not a valid type, no matter where.
