### ISSUE TITLE
Facing with Swagger UI integration with Jersey : javax.servlet.ServletException: java.lang.NoSuchMethodError: scala.collection.JavaConverters$.mapAsScalaMapConverter(Ljava/util/Map;)Lscala/collection/JavaConverters$AsScala;

### ISSUE THREAD

**Issue by neeraj338** [swagger-api/swagger-core#1459]
GlassFish server logs :

[2015-09-25T02:49:39.357+0530] [glassfish 4.1] [SEVERE] [] [com.sun.jersey.spi.container.ContainerResponse] [tid: _ThreadID=26 _ThreadName=http-listener-1(1)] [timeMillis: 1443129579357] [levelValue: 1000] [[
  The exception contained within MappableContainerException could not be mapped to a response, re-throwing to the HTTP container
java.lang.NoSuchMethodError: scala.collection.JavaConverters$.mapAsScalaMapConverter(Ljava/util/Map;)Lscala/collection/JavaConverters$AsScala;
    at com.wordnik.swagger.jersey.listing.ApiListingResource.paramsToMap(ApiListing.scala:152)
    at com.wordnik.swagger.jersey.listing.ApiListingResource$$anonfun$3$$anonfun$apply$4.apply(ApiListing.scala:84)
    at com.wordnik.swagger.jersey.listing.ApiListingResource$$anonfun$3$$anonfun$apply$4.apply(ApiListing.scala:83)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at com.wordnik.swagger.jersey.listing.ApiListingResource$$anonfun$3.apply(ApiListing.scala:83)
    at com.wordnik.swagger.jersey.listing.ApiListingResource$$anonfun$3.apply(ApiListing.scala:82)
    at scala.Option.map(Option.scala:145)
    at com.wordnik.swagger.jersey.listing.ApiListingResource.resourceListing(ApiListing.scala:82)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)

**Comment by webron** [comment]
Please try upgrading to the latest version of swagger-core and retest it. It looks like you're using a fairly old version.
