### ISSUE TITLE
Null Pointer exception in SpecFilter.java

### ISSUE THREAD

**Issue by arunspec5** [swagger-api/swagger-core#1460]
I am getting null pointer exception in the SpecFilter.java. The issue is coming due to definitions.getProperties() returning null by default. Will there be any fix related to this on the release 1.5.4 or is there any work around updated to resolve this issue

        at com.wordnik.swagger.core.filter.SpecFilter.filterDefinitions(SpecFilter.java:61)
	at com.wordnik.swagger.core.filter.SpecFilter.filter(SpecFilter.java:49)
	at com.wordnik.swagger.jaxrs.listing.ApiListingResource.getListingJson(ApiListingResource.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:611)

**Comment by mar612** [comment]
Have you tried the latest stable version of swagger-core, i.e. 1.5.3?  It looks like you're using an out-of-date version, because the package name changed with 1.5.0 from com.wordnik.swagger to io.swagger.

**Comment by webron** [comment]
@arunspec5 - indeed, please upgrade to the latest version and report back.

**Comment by arunspec5** [comment]
Yes Ron. I have tried with the new version and it is working

**Comment by webron** [comment]
Thanks for the update!
