### ISSUE TITLE
Swagger 1.5.3 not able to read the JSON for Jersey2.17

### ISSUE THREAD

**Issue by vishakMetric** [swagger-api/swagger-core#1484]
Hi Team,

  <p>  I have configured the Swagger1.5.3 and i configured the application. Please find the information below

1] Added the gradle download 'io.swagger:swagger-jaxrs:1.5.3'

2] Added all the jars and dependents listed below
a) Jackson Libraries
b)swagger-jersey2-jaxrs-1.5.3
c)swagger-annotations-1.5.3
d)swagger-core-1.5.3
e)swagger-jaxrs-1.5.3
f)swagger-models-1.5.3
g)reflections-0.9.9

No Scala libraries as the dependencies are removed.</p>
<p>
3] In Web.xml configured the following properties
</p>
<p>

< servlet> 
<br>
    < servlet-name>Jersey2Config <  /servlet-name>
<br>
     < servlet-class>io.swagger.jersey.config.JerseyJaxrsConfig < /servlet-class>
<br>
    < init-param>
<br>
      < param-name>api.version< /param-name>
<br>
      < param-value>1.0< /param-value>
<br>
    < /init-param>
<br/>
    < init-param>
<br/>
      < param-name>swagger.api.basepath< /param-name>
<br/>
      < param-value>http://localhost/swagger/api/1.0< /param-value>
<br/>
    < /init-param>
<br/>
  < /servlet>
<br/>

< servlet>
<br/>
   < servlet-name>Jersey REST Service</ servlet-name> 
<br/>
< servlet-class>org.glassfish.jersey.servlet.ServletContainer</ servlet-class>
<br/>
        < init-param>
<br/>
            < param-name>jersey.config.server.provider.packages</ param-name>
<br/>
            < param-value>io.swagger.jaxrs.listing</ param-value>
<br/>
        </ init-param>
<br/>
        < init-param>
<br/>
            < param-name>jersey.config.server.provider.classnames< /param-name>
<br/>
            < param-value>org.glassfish.jersey.media.multipart.MultiPartFeature< /param-value>
 <br/>
        < /init-param>
<br/>
</ servlet> 
<br/>
</p><p>
When i try to access http://localhost/swagger/index.html "swagger" is my context root.

I get the error Can't read swagger JSON from http://localhost/swagger/api/1.0/api-docs

However if i try http://localhost/swagger/sample.json  it loads the static JSON.

Can anyone please help me in this context. </p>

Regards
Vishak

**Comment by iushankin** [comment]
@vishakMetric please check default value of `url` in your index.html file
you can look at sample: https://github.com/swagger-api/swagger-samples/blob/master/java/java-jersey2/src/main/webapp/index.html#L30

Also, check next url: http://localhost/swagger/index.html?url=http://localhost/swagger/sample.json

**Comment by vishakMetric** [comment]
java.lang.IllegalArgumentException: Unrecognized Type: [null]
	at com.fasterxml.jackson.databind.type.TypeFactory._constructType(TypeFactory.java:405)
	at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:354)
	at com.fasterxml.jackson.databind.ObjectMapper.constructType(ObjectMapper.java:1330)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:94)
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:345)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:149)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:129)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:94)
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)
	at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:58)
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:765)
	at io.swagger.jaxrs.Reader.read(Reader.java:263)
	at io.swagger.jaxrs.Reader.read(Reader.java:167)
	at io.swagger.jaxrs.Reader.read(Reader.java:144)
	at io.swagger.jaxrs.listing.ApiListingResource.scan(ApiListingResource.java:64)
	at io.swagger.jaxrs.listing.ApiListingResource.process(ApiListingResource.java:90)
	at io.swagger.jaxrs.listing.ApiListingResource.getListingJson(ApiListingResource.java:129)
	at io.swagger.jaxrs.listing.ApiListingResource.getListing(ApiListingResource.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:164)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:181)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:158)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:101)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:305)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:288)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1110)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:401)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:222)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.xxx.xxx.xxx.swagger.SwaggerApiFilter.doFilter(SwaggerApiFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
	at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
	at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:774)
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:703)
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:896)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
	at java.lang.Thread.run(Thread.java:722)

This is the error i'm getting
public void doFilter(ServletRequest request, ServletResponse response,
			FilterChain chain) throws IOException, ServletException {
		HttpServletResponse res = (HttpServletResponse) response;
		res.addHeader("Access-Control-Allow-Origin", "*");
		res.addHeader("Access-Control-Allow-Methods", "GET, POST, DELETE, PUT");
		res.addHeader("Access-Control-Allow-Headers", "Content-Type");
		chain.doFilter(request, response);
	}

I'm struck.

**Comment by fehguy** [comment]
Hmm, that message is odd.  Can you please share your method signature that it's failing on?

**Comment by vishakMetric** [comment]
Hi fehguy,

   I was able to solve the issue, now i'm not getting those exceptions. Currently i'm facing another issue.
<b>http://localhost/swagger/sample.json</b> is able to fetch all the details and also producing the json.
But it gets struck with below message in UI
<b>fetching resource list: http://localhost/swagger/swagger.json; Please wait.</b>
From the firebug I was able to find the errors listed below
The 'help' tag conflicts with a SwaggerClient function/property name.  Use 'client._help' or 'client.apis.help' instead of 'client.help'.
swagger-ui.js (line 1599)

The 'help' tag conflicts with a SwaggerClient operation function/property name.  Use 'client.apis._help' instead of 'client.apis.help'.
swagger-ui.js (line 1599)

The 'help' tag conflicts with a SwaggerClient function/property name.  Use 'client._help' or 'client.apis.help' instead of 'client.help'.
swagger-ui.js (line 1599)

The 'help' tag conflicts with a SwaggerClient operation function/property name.  Use 'client.apis._help' instead of 'client.apis.help'.
swagger-ui.js (line 1599)

The 'help' tag conflicts with a SwaggerClient function/property name.  Use 'client._help' or 'client.apis.help' instead of 'client.help'.
swagger-ui.js (line 1599)

The 'help' tag conflicts with a SwaggerClient operation function/property name.  Use 'client.apis._help' instead of 'client.apis.help'.
swagger-ui.js (line 1599)

The 'help' tag conflicts with a SwaggerClient function/property name.  Use 'client._help' or 'client.apis.help' instead of 'client.help'.
swagger-ui.js (line 1599)

The 'help' tag conflicts with a SwaggerClient operation function/property name.  Use 'client.apis._help' instead of 'client.apis.help'.
swagger-ui.js (line 1599)

TypeError: Argument 1 of XMLSerializer.serializeToString does not implement interface Node.
swagger-ui.js (line 4327, col 25)

Following are the javascript files
1] backbone-min.js
2] handlebars-2.0.0.js
3] highlight.7.3.pack.js
4] jquery.ba-bbq.min.js
5] jquery.slideto.min.js
6] jquery.wiggle.min.js
7] jquery-1.8.0.min.js
8] marked.js
9] swagger-oauth.js
10]swagger-ui.js
11] swagger-ui.min.js
12] underscore-min.js
13] underscore-min.map

I have tested it in Firefox [41] and Chrome [31] both the places getting same result.
Can you please let me know what i have missed.

**Comment by webron** [comment]
It looks like in one case you're loading `http://localhost/swagger/sample.json` and in the other you're loading `http://localhost/swagger/swagger.json`. Is that really what's happening?

**Comment by vishakMetric** [comment]
I did the change but still same thing is happening.
`<div class='input'><input placeholder="http://localhost/metricstream/api/7.0swagger/swagger.json" id="input_baseUrl" name="baseUrl" type="text"/></div>`
and 
`$(function () {
      var url = window.location.search.match(/url=([^&]+)/);
      if (url && url.length > 1) {
        url = decodeURIComponent(url[1]);
      } else {
        url = "http://localhost/swagger/swagger.json";
      }
      window.swaggerUi = new SwaggerUi({
        url: url,
        dom_id: "swagger-ui-container",
        supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
        onComplete: function(swaggerApi, swaggerUi){
          if(typeof initOAuth == "function") {
            initOAuth({
              clientId: "your-client-id",
              realm: "your-realms",
              appName: "your-app-name"
            });
          }`

**Comment by fehguy** [comment]
Hi @vishakMetric, this is really sounding like a swagger-ui issue.  Please reopen an issue in that project if you're still seeing problems.

**Comment by vishakMetric** [comment]
This can be further tracked from Swagger-ui below is the url
`https://github.com/swagger-api/swagger-ui/issues/1685`
