### ISSUE TITLE
ApiImplicitParam of dataType="file" leads to an error log

### ISSUE THREAD

**Issue by pjfanning** [swagger-api/swagger-core#1653]
Hi,
I'm using an annotation:
`new ApiImplicitParam(name = "body", value = "binary data", required = true, dataType = "file", paramType = "body")
  ))`
The swagger.json that is generated from swagger-json still seems fine but it would be nice not to have the exception generated. I have checked the swagger.json in the Swagger UI.

`
[07-Feb-2016 21:11:13.901 GMT] ERROR [io.swagger.util.ReflectionUtils] Failed to resolve 'file' into class
java.lang.ClassNotFoundException: file
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.swagger.util.ReflectionUtils.typeFromString(ReflectionUtils.java:29)
	at io.swagger.jaxrs.Reader.readImplicitParam(Reader.java:436)
	at io.swagger.jaxrs.Reader.readImplicitParameters(Reader.java:412)
	at io.swagger.jaxrs.Reader.read(Reader.java:399)
	at io.swagger.jaxrs.Reader.read(Reader.java:147)
	at com.github.swagger.spray.SwaggerHttpService$class.swagger(SwaggerHttpService.scala:54)
`

**Comment by webron** [comment]
The spec doesn't support file uploads with `body` parameters but rather `formData` parameters. See #1319 for more details.

**Comment by pjfanning** [comment]
Thanks Webron for the advise. Using dataType="java.io.InputStream" seems to work well in this case.
I do have a similar stacktrace for a multipart form param though.
`new ApiImplicitParam(name = "file", value = "xls[m,x] file", required = true, dataType = "file", paramType = "formData")`
