### ISSUE TITLE
swagger-models 1.5.7 has an incompatible signature-change in io.swagger.models.Property

### ISSUE THREAD

**Issue by vivin** [swagger-api/swagger-core#1667]
[This commit](https://github.com/swagger-api/swagger-core/commit/a325b1e62aa87f1d9941cb90a091cbda4962194d) changed the signature of `setExample` in `Properties` from `Properties#setExample(String)` to `Properties#setExample(Object)`. This can cause issues at runtime. I noticed this while building swagger-codegen from source and using it in a project that depends on springfox-swagger2, which brings in 1.5.6 of swagger-models as a dependency. 

If the 1.5.6 version ends up getting loaded first, code-generation fails with the following error:

```
java.lang.NoSuchMethodError: io.swagger.models.properties.Property.getExample()Ljava/lang/Object;
	at io.swagger.codegen.DefaultCodegen.toExampleValue(DefaultCodegen.java:601) ~[swagger-codegen-2.1.6-SNAPSHOT.jar:2.1.6-SNAPSHOT]
	at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:983) ~[swagger-codegen-2.1.6-SNAPSHOT.jar:2.1.6-SNAPSHOT]
	at io.swagger.codegen.DefaultCodegen.addVars(DefaultCodegen.java:1990) ~[swagger-codegen-2.1.6-SNAPSHOT.jar:2.1.6-SNAPSHOT]
	at io.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:936) ~[swagger-codegen-2.1.6-SNAPSHOT.jar:2.1.6-SNAPSHOT]
	at io.swagger.codegen.languages.JavaClientCodegen.fromModel(JavaClientCodegen.java:510) ~[swagger-codegen-2.1.6-SNAPSHOT.jar:2.1.6-SNAPSHOT]
	at io.swagger.codegen.DefaultGenerator.processModels(DefaultGenerator.java:744) ~[swagger-codegen-2.1.6-SNAPSHOT.jar:2.1.6-SNAPSHOT]
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:196) ~[swagger-codegen-2.1.6-SNAPSHOT.jar:2.1.6-SNAPSHOT]
```

If you override the transitive dependency and force 1.5.7, springfox ends up throwing the following error because it cannot find `Property#setExample(String)`:

```
java.lang.NoSuchMethodError: io.swagger.models.properties.Property.setExample(Ljava/lang/String;)V
	at springfox.documentation.swagger2.mappers.ModelMapper.mapProperty(ModelMapper.java:171) ~[springfox-swagger2-2.3.2-SNAPSHOT.jar:2.3.2-SNAPSHOT]
	at springfox.documentation.swagger2.mappers.ModelMapper.mapProperties(ModelMapper.java:106) ~[springfox-swagger2-2.3.2-SNAPSHOT.jar:2.3.2-SNAPSHOT]
	at springfox.documentation.swagger2.mappers.ModelMapper.mapProperties(ModelMapper.java:82) ~[springfox-swagger2-2.3.2-SNAPSHOT.jar:2.3.2-SNAPSHOT]
	at springfox.documentation.swagger2.mappers.ModelMapper.mapModels(ModelMapper.java:67) ~[springfox-swagger2-2.3.2-SNAPSHOT.jar:2.3.2-SNAPSHOT]
	at springfox.documentation.swagger2.mappers.ModelMapper.modelsFromApiListings(ModelMapper.java:202) ~[springfox-swagger2-2.3.2-SNAPSHOT.jar:2.3.2-SNAPSHOT]
	at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2MapperImpl.mapDocumentation(ServiceModelToSwagger2MapperImpl.java:50) ~[springfox-swagger2-2.3.2-SNAPSHOT.jar:2.3.2-SNAPSHOT]
	at springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(Swagger2Controller.java:81) ~[springfox-swagger2-2.3.2-SNAPSHOT.jar:2.3.2-SNAPSHOT]
```

I'm using a snapshot version of springfox-swagger2, but the issue should be present in earlier versions since this change was only made 19 days ago.

IMO the right change might be to mark `Properties#setExample(String)` as deprecated instead of removing it outright, especially since this is a patch-release that shouldn't break backwards compatibility.

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-core/pull/1668
