### ISSUE TITLE
Error handling default value for Integer

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-core#1673]
In https://www.neutrinoapi.com/api/swagger.json, some default value for integer type are decimal ("6.0" for example), which causes the following exception:
```
[main] WARN io.swagger.models.parameters.AbstractSerializableParameter - Illegal DefaultValue 6.0 for parameter type integer
java.lang.NumberFormatException: For input string: "6.0"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Long.parseLong(Long.java:441)
    at java.lang.Long.valueOf(Long.java:540)
    at io.swagger.models.parameters.AbstractSerializableParameter.getDefault(AbstractSerializableParameter.java:193)
    at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:466)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:639)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128)
    at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:800)
    at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:676)
    at io.swagger.util.Json.pretty(Json.java:23)
    at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1553)
    at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1389)
    at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:624)
    at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:571)
    at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:279)
    at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
    at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
```

Ref: https://github.com/swagger-api/swagger-codegen/issues/2203

**Comment by webron** [comment]
@wing328 does it really make sense to handle it though? The spec *is* faulty. 

From:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterDefault
> Unlike JSON Schema this value MUST conform to the defined type for this parameter.

**Comment by wing328** [comment]
Agree with you that the spec is faulty and the spec owner/user should fix it.

My PR aims to handle the exception gracefully.

**Comment by webron** [comment]
Ugh, sorry for the late reply @wing328. By doing that though, you're not letting the spec author know that they have a problem, you silently fix it. If the person put a value of 6.4, would you still want to convert. Looking at the discussion in the leading issue in codegen, the user admits that it is not technically an integer (and, well, it really isn't). Makes much more sense to me to throw an exception in this case and force the user to fix their spec.

**Comment by wing328** [comment]
My original intention is to handle the minor issue gracefully for the user. You've the point that the user should be notified of the error so that they can fix it.
