### ISSUE TITLE
NullPointerException with SwaggerSpecFilter

### ISSUE THREAD

**Issue by ptwohig** [swagger-api/swagger-core#1677]
Running Swagger 1.5.7 and I get this.  My filter is very simple, in fact all it is designed to do is simply pass all through.  I plan on toggling various filters based on the current user, but the default "pass all" should work without exception.

```
java.lang.NullPointerException
	at io.swagger.core.filter.SpecFilter.filterDefinitions(SpecFilter.java:69)
	at io.swagger.core.filter.SpecFilter.filter(SpecFilter.java:54)
	at io.swagger.jaxrs.listing.ApiListingResource.getListingJson(ApiListingResource.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)`
```

Filter code is as follows:

```
public class PassAllSwaggerSpecFilter extends AbstractSpecFilter {}
```

**Comment by ptwohig** [comment]
Mistake in my configuration.
