### ISSUE TITLE
JAX-RS Bean Params are treated as bodies

### ISSUE THREAD

**Issue by johnament** [swagger-api/swagger-core#1720]
Suppose I have a bean param defined like this:

```
public class GenerateReportCommand {
    @PathParam("reportKey")
    private String reportKey;
    @DefaultValue("all") @QueryParam("eventType")
    private String eventType;
```

In the rest endpoint

```
    @Path("/{reportKey}")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    Response generateReport(@BeanParam GenerateReportCommand generateReportCommand);
```

The generated swagger.json indicates that the bean param is a body, even on a get, instead of parsing the query and path params.

**Comment by webron** [comment]
Which swagger-core dependency do you use?

**Comment by johnament** [comment]
I believe it's 1.5.7.

**Comment by webron** [comment]
Not the version, which of the modules? swagger-jaxrs? swagger-jersey?

**Comment by johnament** [comment]
Oh ok.  jaxrs.

**Comment by webron** [comment]
so jaxrs doesn't have support for `@BeanParam`. If you want support for it, you'll have to use swagger-jersey2-jaxrs, whether you use jersey2 or not.

**Comment by johnament** [comment]
That doesn't make sense, why would I use a jersey library when I'm not using jersey?

Can support for BeanParam be moved into jaxrs instead of jersey?  This is a core capability of JAX-RS, not a feature unique to jersey.

**Comment by webron** [comment]
It's a core capability of jax-rs2, not jax-rs. And for now, that's how the project is structured, and we won't be able to change it soon (we have a ticket on that). 

At the moment, if you want support for BeanParam, you'd have to use that dependency.

**Comment by johnament** [comment]
The problem is that jersey2-jaxrs has a hard dependency on jersey.  I'm using resteasy.  I can't bring in jersey.

https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jersey2-jaxrs/pom.xml#L74

**Comment by webron** [comment]
Bringing in Jersey2 should have no effect on your application, other than making the dependency larger. You can try excluding the jersey2 dependency from our dependency and see if it works, but I cannot guarantee that.

**Comment by m-radzikowski** [comment]
Using `swagger-jersey-jaxrs` package instead of `swagger-jaxrs` causes deployment error on WildFly 10 with RestEasy (I've swagger configured by annotations if that matters):
```java
14:30:54,961 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 262) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./: java.lang.RuntimeException: RESTEASY003920: Unable to instantiate ContextResolver
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.RuntimeException: RESTEASY003920: Unable to instantiate ContextResolver
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1641)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1344)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1266)
	at org.jboss.resteasy.spi.ResteasyDeployment.registerProvider(ResteasyDeployment.java:552)
	at org.jboss.resteasy.spi.ResteasyDeployment.registration(ResteasyDeployment.java:342)
	at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:245)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:113)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:231)
	at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:132)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:526)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:101)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
	... 6 more
Caused by: java.lang.IllegalArgumentException: RESTEASY003900: Unable to find a public constructor for provider class org.glassfish.jersey.media.multipart.MultiPartProperties$Feature$MultiPartContextResolver
	at org.jboss.resteasy.spi.ResteasyProviderFactory.createConstructorInjector(ResteasyProviderFactory.java:2218)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2207)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.addContextResolver(ResteasyProviderFactory.java:1106)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1635)
	... 21 more
```
so right now I suppose I've to wait for swagger-jaxrs2 module with `@BeanParam` support.
