### ISSUE TITLE
beanConfig.setResourcePackage("com.my.rest.resource"); is causing com.sun.jersey.api.container.ContainerException

### ISSUE THREAD

**Issue by madhugarimilla** [swagger-api/swagger-core#1774]
I am trying to initalize swagger inside my Application class using the below code

```
import io.swagger.jaxrs.config.BeanConfig;
import io.swagger.jaxrs.listing.ApiListingResource;
import io.swagger.jaxrs.listing.SwaggerSerializers;

import java.util.HashSet;
import java.util.Set;

import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

import com.my.rest.resource.HelloWorldService;

@ApplicationPath("/")
public class JerseyApplication extends Application {

    public JerseyApplication() {
        super();
        BeanConfig beanConfig = new BeanConfig();
        beanConfig.setVersion("1.0.2");
        beanConfig.setHost("http://localhost:7070");
        beanConfig.setBasePath("/api");
        beanConfig.setResourcePackage("com.my.rest.resource");
        beanConfig.setScan(true);
        beanConfig.setPrettyPrint(true);

    }

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> result = new HashSet<Class<?>>();
        result.add(HelloWorldService.class);
        result.add(ApiListingResource.class);
        result.add(SwaggerSerializers.class);
        return result;
    }
}
```

and here is my OSGI Activator class

```
import io.swagger.jaxrs.config.BeanConfig;
import java.util.Dictionary;
import java.util.Hashtable;
import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import org.osgi.framework.BundleActivator;
import org.osgi.framework.BundleContext;
import org.osgi.framework.ServiceReference;
import org.osgi.service.http.HttpService;
import org.osgi.service.http.NamespaceException;
import org.osgi.util.tracker.ServiceTracker;
import com.my.rest.api.filters.AuthFilter;
import com.sun.jersey.spi.container.servlet.ServletContainer;

public class Activator implements BundleActivator {

    private static BundleContext context;

    private ServiceTracker tracker;

    private HttpService httpService = null;

    static BundleContext getContext() {
        return context;
    }

    public void start(BundleContext bundleContext) throws Exception {
        Activator.context = bundleContext;

        this.tracker = new ServiceTracker(Activator.context, HttpService.class.getName(), null){
            @Override
            public Object addingService(ServiceReference reference) {
                httpService = (HttpService) super.addingService(reference);
                registerServlets();
                return httpService;
            }

            @Override
            public void removedService(ServiceReference reference,
                    Object service) {
                 if (httpService == service) {
                     unregisterServlets();
                     httpService = null;
                 }
                 super.removedService(reference, service);
            }
        };

        this.tracker.open();

    }

    public void stop(BundleContext bundleContext) throws Exception {
        Activator.context = null;
        this.tracker.close();
    }

    private void registerServlets() {
        try {
            rawRegisterServlets();
        } catch (Exception ie) {
            throw new RuntimeException(ie);
        }
    }

    private void rawRegisterServlets() throws ServletException, NamespaceException, InterruptedException {
            httpService.registerServlet("/rest/v1", new ServletContainer(), getJerseyServletParams(), null);
    }

    private void unregisterServlets() {
        if (this.httpService != null) {
            httpService.unregister("/rest/v1");
        }
    }

    private Dictionary<String, String> getJerseyServletParams() {
        Dictionary<String, String> jerseyServletParams = new Hashtable();
        jerseyServletParams.put("javax.ws.rs.Application", JerseyApplication.class.getName());
        return jerseyServletParams;
    }
}
```

It is throwing the below exception. If i comment out beanConfig.setResourcePackage("com.my.rest.resource"); from my Application class then it doesn't throw the exception but no resources are being identified.

`Caused by: com.sun.jersey.api.container.ContainerException: The Application class com.my.rest.api.JerseyApplication could not be instantiated
    at com.sun.jersey.server.impl.application.DeferredResourceConfig$ApplicationHolder.<init>(DeferredResourceConfig.java:88)
    at com.sun.jersey.server.impl.application.DeferredResourceConfig$ApplicationHolder.<init>(DeferredResourceConfig.java:79)
    at com.sun.jersey.server.impl.application.DeferredResourceConfig.getApplication(DeferredResourceConfig.java:76)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1164)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:180)
    at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:799)
    at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:795)
    at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:795)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:790)
    at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:509)
    at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:339)
    at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)
    at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
    at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:394)
    at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:577)
    at javax.servlet.GenericServlet.init(GenericServlet.java:244)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.init(ServletRegistration.java:49)
    at org.eclipse.equinox.http.servlet.internal.ProxyServlet.registerServlet(ProxyServlet.java:184)
    at org.eclipse.equinox.http.servlet.internal.HttpServiceImpl.registerServlet(HttpServiceImpl.java:66)
    at com.my.rest.api.Activator.rawRegisterServlets(Activator.java:88)
    at com.my.rest.api.Activator.registerServlets(Activator.java:80)`

**Comment by fehguy** [comment]
Please share a sample project if you're still having issues.

**Comment by webron** [comment]
@GADNT Which version of swagger-core are you using?

**Comment by GADNT** [comment]
@webron I'm using swagger-core 1.5.0

**Comment by webron** [comment]
@GADNT It's time to update to 1.5.12.

**Comment by GADNT** [comment]
@webron Thanks for your suggestions, but no luck with 1.5.12. I am trying to deploy to a Weblogic and yes is with jersey 1.18 provided by Weblogic.

**Comment by GADNT** [comment]
Any thoughts related my issue?

**Comment by fehguy** [comment]
@GADNT please see my comment: https://github.com/swagger-api/swagger-core/issues/1774#issuecomment-269110771
