### ISSUE TITLE
Conflicting setter definitions for property \“currency\”: javax.money.MonetaryAmountFactory

### ISSUE THREAD

**Issue by vijayaratha** [swagger-api/swagger-core#1805]
I'm using io.swagger 1.5.9 version. I use **org.javamoney.moneta.Money**  type in my REST endpoints. I register them in the RestApplication. When deploying my war file i get following exception[1]

```java
import io.swagger.jaxrs.config.BeanConfig;

import java.util.HashSet;
import java.util.Set;

import javax.ws.rs.ApplicationPath;

@ApplicationPath("/rest")
public class RestApplication extends Application {
    public RestApplication() {
        BeanConfig beanConfig = new BeanConfig();
        // beanConfig.setVersion("1.0");
        beanConfig.setSchemes(new String[] { "http" });
        beanConfig.setTitle("My API");
        beanConfig.setBasePath("/rest");
        beanConfig.setResourcePackage("com.test.rest.autogen");
        beanConfig.setScan(true);
    }
```

```
@Override
public Set<Class<?>> getClasses() {
    HashSet<Class<?>> set = new HashSet<Class<?>>();
    set.add(com.test.DurtaionConverterProvider.class);
    set.add(com.test.LocalDateTimeConverterProvider.class);
    set.add(com.test.MoneyConverterProvider.class);
       set.add(SalesEndpoint.class);
    set.add(AddressEndpoint.class);

          set.add(io.swagger.jaxrs.listing.ApiListingResource.class);
    set.add(io.swagger.jaxrs.listing.SwaggerSerializers.class);

    return set;
}
}
```

```
[1]
_0:35:41,056 ERROR [org.jboss.msc.service.fail](ServerService Thread Pool -- 185) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./test2dbwar: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./test2dbwar: java.lang.IllegalArgumentException: Conflicting setter definitions for property "currency": javax.money.MonetaryAmountFactory#setCurrency(1 params) vs javax.money.MonetaryAmountFactory#setCurrency(1 params)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.IllegalArgumentException: Conflicting setter definitions for property "currency": javax.money.MonetaryAmountFactory#setCurrency(1 params) vs javax.money.MonetaryAmountFactory#setCurrency(1 params)
    at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getSetter(POJOPropertyBuilder.java:293)
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:246)
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:127)
    at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99)
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:106)
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:71)
    at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:342)
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:127)
    at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99)
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:106)
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:71)
    at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:342)
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:127)
    at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99)
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:106)
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:71)
    at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:342)
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:127)
    at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99)
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:106)
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:71)
    at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)
    at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:58)
    at io.swagger.util.ParameterProcessor.applyAnnotations(ParameterProcessor.java:175)
    at io.swagger.jaxrs.Reader.getParameters(Reader.java:914)
    at io.swagger.jaxrs.Reader.parseMethod(Reader.java:852)
    at io.swagger.jaxrs.Reader.read(Reader.java:293)
    at io.swagger.jaxrs.Reader.read(Reader.java:145)
    at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:223)
    at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:204)_
```

**Comment by fehguy** [comment]
please share the pojo that is giving this issue.
