### ISSUE TITLE
java.lang.IllegalArgumentException: Conflicting setter definitions for property "inMemoryFormat": com.hazelcast.config.NearCacheConfig#setInMemoryFormat(1 params) vs com.hazelcast.config.NearCacheConfig#setInMemoryFormat(1 params)

### ISSUE THREAD

**Issue by panqingcui** [swagger-api/swagger-core#1809]
HI
   This class is not scanned, but this exception appears.
```
java.lang.IllegalArgumentException: Conflicting setter definitions for property "inMemoryFormat": com.hazelcast.config.NearCacheConfig#setInMemoryFormat(1 params) vs com.hazelcast.config.NearCacheConfig#setInMemoryFormat(1 params)
    at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getSetter(POJOPropertyBuilder.java:303)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:267)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:149)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:129)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:94)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:358)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:149)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:129)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:94)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:108)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:94)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:358)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:149)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:129)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:94)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:358)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:149)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:129)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:94)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:358)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:149)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:129)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:94)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:58)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jaxrs.Reader.parseMethod(Reader.java:765)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
    at io.swagger.jaxrs.Reader.read(Reader.java:263)[231:oplate-service-register-discovery:1.1.0.SNAPSHOT]
```

**Comment by fehguy** [comment]
Please share more details and re-open.
