### ISSUE TITLE
jax-rs @BeanParam with constructor results in NPE

### ISSUE THREAD

**Issue by dsmiley** [swagger-api/swagger-core#1819]
I have a parameter that is annotated with \@BeanParam to a class that has a bunch of fields in it.  This class has only getters, not setters, and it has a constructor that takes all parameters.  Those constructor parameters are annotated with \@QueryParam, \@Size, \@ApiParam etc. Jersey is able to handle this fine but Swagger throws an exception:

```
Exception in thread "main" java.lang.IllegalArgumentException: Unrecognized Type: [null]
    at com.fasterxml.jackson.databind.type.TypeFactory._fromAny(TypeFactory.java:1110)
    at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:563)
    at io.swagger.jaxrs.ext.AbstractSwaggerExtension.constructType(AbstractSwaggerExtension.java:53)
    at io.swagger.jaxrs.ext.AbstractSwaggerExtension.shouldIgnoreType(AbstractSwaggerExtension.java:45)
    at io.swagger.jersey.SwaggerJersey2Jaxrs.extractParameters(SwaggerJersey2Jaxrs.java:40)
    at io.swagger.jersey.SwaggerJersey2Jaxrs.extractParameters(SwaggerJersey2Jaxrs.java:82)
    at io.swagger.jaxrs.Reader.getParameters(Reader.java:913)
    at io.swagger.jaxrs.Reader.parseMethod(Reader.java:864)
    at io.swagger.jaxrs.Reader.read(Reader.java:299)
    at io.swagger.jaxrs.Reader.read(Reader.java:145)
    at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:223)
    at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:204)
```

I believe the bug is in io.swagger.jersey.SwaggerJersey2Jaxrs.extractParameters?

FWIW my code is in Kotlin but that shouldn't matter.  I viewed the decompiled class to verify what it looked like.

**Comment by dsmiley** [comment]
My work-around is of course to make the state be set via setters.  I'd rather not do that though, and the IAE from Swagger is arguably something that should be dealt with somehow.

**Comment by webron** [comment]
Would be hard to debug without seeing the equivalent in Java. If you feel you can submit a PR to resolve the issue, please do so.

**Comment by dsmiley** [comment]
Why was this closed?

**Comment by fehguy** [comment]
A PR with an example showing the issue would make it possible to solve
