### ISSUE TITLE
ConcurrentModificationException when using SwaggerSpecFilter

### ISSUE THREAD

**Issue by srl295** [swagger-api/swagger-core#1831]
When using a `SwaggerSpecFilter`, `GET …/swagger.json` fails when accessed by as few as 3 clients.

Partial stack trace (1.5.7):
```
[err] java.util.ConcurrentModificationException
[err] 	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711)
[err] 	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:734)
[err] 	at io.swagger.core.filter.SpecFilter.filterDefinitions(SpecFilter.java:200)
[err] 	at io.swagger.core.filter.SpecFilter.filter(SpecFilter.java:86)
[err] 	at io.swagger.jaxrs.listing.ApiListingResource.process(ApiListingResource.java:121)
[err] 	at io.swagger.jaxrs.listing.ApiListingResource.getListingJson(ApiListingResource.java:154)
[err] 	at io.swagger.jaxrs.listing.ApiListingResource.getListing(ApiListingResource.java:141)
[err] 	at sun.reflect.GeneratedMethodAccessor168.invoke(Unknown Source)
[err] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[err] 	at java.lang.reflect.Method.invoke(Method.java:498)
[err] 	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:607)
[err] 	at [internal classes]
[err] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
[err] 	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:99)
…
```

Code to reproduce:
```
        FilterFactory.setFilter(new SwaggerSpecFilter() {
            public boolean isPropertyAllowed(Model model, Property property, String propertyName,
                    Map<String, List<String>> params, Map<String, String> cookies, Map<String, List<String>> headers) {
                return true;
            }
            public boolean isParamAllowed(Parameter parameter, Operation operation, ApiDescription api,
                    Map<String, List<String>> params, Map<String, String> cookies, Map<String, List<String>> headers) {
                return true;
            }

            public boolean isOperationAllowed(Operation operation, ApiDescription api, Map<String, List<String>> params,
                    Map<String, String> cookies, Map<String, List<String>> headers) {
                return true;
            }
        });
```

**Comment by srl295** [comment]
We're not trying to modify the spec on every request. We're just trying to switch off some operations based on **static** (configuration) parameters.  Would it be possible to have some kind of spec filter that's just called one time and then cached? It wouldn't have headers, cookies, etc.

**Comment by fehguy** [comment]
It's so fast to mutate on each request, that's the recommended way to go.  The other way you can hide things is using the `hidden=true` property which is available in most annotations.  Those will cause things to be skipped by the processor.  You have more control with the spec filter.

**Comment by srl295** [comment]
@fehguy right, but we need to hide based on the configuration, not just the annotations. Is there any way to get one-time configuration and caching?

**Comment by fehguy** [comment]
no, but you do realize that the Spec Filter is going to run in milliseconds, right?  That's the design to use, or you can extend the ApiListingResource and cache it yourself.

**Comment by webron** [comment]
Just pushed 1.5.10-SNAPSHOT with the change, feel free to take it for a spin.
