### ISSUE TITLE
Incorrect default values is generated for integer type parameters

### ISSUE THREAD

**Issue by guser11** [swagger-api/swagger-core#1871]
Swagger generated default values for integer type are coming as float values
For example
@QueryParam("offset") @DefaultValue("0")
the swaager it generates is 
{"name":"offset",
"in":"query",
"required":false,
"type":"integer",
"default":0.0,
"format":"int32"}

here the default value should come as 0 not 0.0
because of this while generating SDK it throws following error
WARN io.swagger.models.parameters.AbstractSerializableParameter - Illegal DefaultValue 0.0 for parameter type integer
java.lang.NumberFormatException: For input string: "0.0"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Long.parseLong(Long.java:589)
    at java.lang.Long.valueOf(Long.java:803)
    at io.swagger.models.parameters.AbstractSerializableParameter.getDefault(AbstractSerializableParameter.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:466)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:639)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128)
    at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:800)
    at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:676)
    at io.swagger.util.Json.pretty(Json.java:23)
    at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:2002)
    at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1835)
    at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:733)
    at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:677)
    at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:365)
    at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
    at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)

**Comment by fehguy** [comment]
Please share the whole method definition so we can troubleshoot this.

**Comment by guser11** [comment]
API Controller(Resource)

@GET
@Produces( { MediaType.APPLICATION_JSON })
@Path("id")
@ApiOperation(value = "Get user's Account by userId")
public User get(@BeanParam UserParam params)
{
  //looks for user id

}

And UserParam Class:

public class UserParam {

	private int offset;
	

	public int getOffset() {

        return offset;
    	}

    @QueryParam("offset")
    @DefaultValue("0")
    public void setOffset(int count) {
        this.offset = count;
    }

**Comment by fehguy** [comment]
Please try changing to `Integer` instead of `int` and report back what you get.  Not saying that's the solution but it would help.

**Comment by guser11** [comment]
I tried with integer also:
private Integer offset;
public Integer getOffset() {
        return offset;
    }

    @QueryParam("offset")
    @DefaultValue("0")
    public void setOffset(Integer count) {
        this.offset = count;
    }

but no luck ! still getting 0.0 in swagger.json
{"name":"offset","in":"query","required":false,"type":"integer","default":0.0,"format":"int32"}

**Comment by fehguy** [comment]
OK this is an issue in how numerics are stored internally.  Please follow #1889 for a fix
