### ISSUE TITLE
java.lang.IllegalArgumentException: No enum constant io.swagger.models.auth.In.header

### ISSUE THREAD

**Issue by mdhtr** [swagger-api/swagger-core#1958]
In the 1.5.10 stable release, in swagger-jaxrs, the new @SecurityDefinition @ApiKeyAuthDefinition added in #1840 is unusable, because initializing ApiKeyAuthDefinition.ApiKeyLocation.HEADER or ApiKeyAuthDefinition.ApiKeyLocation.QUERY throws an IllegalArgumentException.

Sample code

```
@SwaggerDefinition(
        info = @Info(
                version = "V0.1",
                title = "MyAPI"
        ),
        securityDefinition = @SecurityDefinition(
                apiKeyAuthDefintions = {
                        @ApiKeyAuthDefinition(key = "apiKeyAuth", name = "apiKey", in = ApiKeyAuthDefinition.ApiKeyLocation.HEADER)}
        )
)
@Api()
@Path("my-class")
public class MyClass {
    //...
}
```

Stack trace

```
Caused by: java.lang.IllegalArgumentException: No enum constant io.swagger.models.auth.In.header
    at java.lang.Enum.valueOf(Enum.java:238)
    at io.swagger.models.auth.In.valueOf(In.java:9)
    at io.swagger.jaxrs.Reader.readSwaggerConfig(Reader.java:492)
    at io.swagger.jaxrs.Reader.read(Reader.java:145)
```

**Comment by devoto13** [comment]
It was fixed in [this commit](https://github.com/swagger-api/swagger-core/commit/964ff7c2dcd8169005995e40a0269124f89d90bc).

**Comment by fehguy** [comment]
Release on the way...
