### ISSUE TITLE
io.swagger.util.ReflectionUtils - Failed to resolve 'number' into class

### ISSUE THREAD

**Issue by wizbot88** [swagger-api/swagger-core#1970]
When I put implicit param annotation with **dataType="number"** on my method.

`@ApiImplicitParams({@ApiImplicitParam(name = "param1", dataType = "number", paramType = "form", required = true)})`

Everytime I launch my application, I got a stacktrace as swagger is trying to find the **class number** (which doesn't exist).

I'm using swagger 1.5.10

`io.swagger.util.ReflectionUtils - Failed to resolve 'number' into class
java.lang.ClassNotFoundException: number
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1714) ~[catalina.jar:7.0.42]
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559) ~[catalina.jar:7.0.42]
	at io.swagger.util.ReflectionUtils.loadClassByName(ReflectionUtils.java:44) ~[swagger-core-1.5.10.jar:1.5.10]
	at io.swagger.util.ReflectionUtils.typeFromString(ReflectionUtils.java:22) ~[swagger-core-1.5.10.jar:1.5.10]
	at io.swagger.jaxrs.Reader.readImplicitParam(Reader.java:438) [swagger-jaxrs-1.5.10.jar:1.5.10]
	at io.swagger.jaxrs.Reader.readImplicitParameters(Reader.java:414) [swagger-jaxrs-1.5.10.jar:1.5.10]
	at io.swagger.jaxrs.Reader.read(Reader.java:401) [swagger-jaxrs-1.5.10.jar:1.5.10]
	at io.swagger.jaxrs.Reader.read(Reader.java:150) [swagger-jaxrs-1.5.10.jar:1.5.10]
	at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:235) [swagger-jaxrs-1.5.10.jar:1.5.10]
	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:214) [swagger-jaxrs-1.5.10.jar:1.5.10]`

However everything is working fine with **swagger-ui** or **swagger-codegen** as number dataType is part of the swagger specification.

**Comment by fehguy** [comment]
in swagger-core, `dataType` is the java class.  Please try `java.math.BigDecimal`, I believe and it should work.

**Comment by wizbot88** [comment]
Thanks for the answer.

Actually, when I try with `java.math.BigDecimal`, I don't have an exception anymore.
But in my swagger.json you can find 
`"parameters":[{"name":"param1","in":"formData","required":true,"type":"java.math.BigDecimal"}]`
The type `"type":"java.math.BigDecimal"` doesn't make any sense in the swagger.json as it is not part of the swagger-spec.

I understand that I have to match a java class in my code to properly override the **dataType**.
However this **dataType** should be translated into a proper **swagger spec dataType** (in this case `number`)

My question is : "is it how this annotation should work ?"

**Comment by fehguy** [comment]
Correct you are, that's not right.  I will test and report back.

**Comment by fehguy** [comment]
This was indeed a bug.  Please pull 1.5.11-SNAPSHOT and report back

**Comment by wizbot88** [comment]
Working great ! Thanks
