### ISSUE TITLE
swagger2Feature is not testable by arquillian on OSGI

### ISSUE THREAD

**Issue by bouskaJ** [swagger-api/swagger-core#2001]
You are using [Reflections](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/BeanConfig.java#L269) to scan the source package. The problem is that arquillain installs new OSGI bundles by JMX and due to possibility of remote installation the location can't be properly set. The Vfs class (used by reflections) can't load the package and I got an exception.
here is the stacktrace:
`java.net.MalformedURLException: no protocol: BasicTest.jar
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.reflections.vfs.Vfs$DefaultUrlTypes$4.createDir(Vfs.java:324)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:108)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:100)
	at org.reflections.Reflections.scan(Reflections.java:237)
	at org.reflections.Reflections.scan(Reflections.java:204)
	at org.reflections.Reflections.<init>(Reflections.java:129)
	at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:256)
	at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:221)
	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:204)
	at org.apache.cxf.jaxrs.swagger.Swagger2Feature.addSwaggerResource(Swagger2Feature.java:111)
	at org.apache.cxf.jaxrs.swagger.AbstractSwaggerFeature.initialize(AbstractSwaggerFeature.java:69)
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.applyFeatures(JAXRSServerFactoryBean.java:252)
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
`

**Comment by fehguy** [comment]
How is this a bug in swagger-core?

**Comment by bouskaJ** [comment]
It is not possible to fix it in Arquillian so if you want to swagger will be testable with Arquillian you have to change something in swagger core.
