### ISSUE TITLE
Errors reported on first requests for swagger.json

### ISSUE THREAD

**Issue by lloyd31** [swagger-api/swagger-core#2005]
I am using JDK 1.6.0_45, JBoss 5 and swagger-jaxrs 1.5.8. The very first requests for swagger.json generates the below error. But subsequent requests provide us the required json\yaml files. Any suggestions why would this happen? Trying to avoid any further confusions over this, even though i feel that this is harmless.

WARN  [Reflections] Could not get URL
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:127)
	at java.util.jar.JarFile.<init>(JarFile.java:136)
	at java.util.jar.JarFile.<init>(JarFile.java:73)
	at org.reflections.vfs.UrlTypeVFS.createDir(UrlTypeVFS.java:45)
	at org.reflections.vfs.Vfs$DefaultUrlTypes$5.createDir(Vfs.java:269)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:99)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
	at org.reflections.Reflections.scan(Reflections.java:237)
	at org.reflections.Reflections.scan(Reflections.java:204)
	at org.reflections.Reflections.<init>(Reflections.java:129)
	at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:256)
	at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:221)

which is triggered by beanConfig.setScan(true).

**Comment by fehguy** [comment]
looks like a dependency issue on your side.

**Comment by webron** [comment]
Note that the minimum requirements for swagger-core is Java 7.

**Comment by lloyd31** [comment]
@webron this error occurs only for the first call for swagger.json. But the next calls provides us appropriate json\yaml files for the next calls. Correct me if my understanding is wrong, but doesn't the swagger scanning trigger for every call?
