### ISSUE TITLE
Getting Class not found exception.

### ISSUE THREAD

**Issue by CatchTheThunder** [swagger-api/swagger-core#2017]
I am updating my whole project from swagger API 1 to API 2.(Swagger 1.5.8)
But while running, i got exception like : java.lang.ClassNotFoundException: java.util.String
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1305)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at io.swagger.util.ReflectionUtils.loadClassByName(ReflectionUtils.java:43)

**code:**
@ApiModel(value = "smdl")
public class ConfigOptions {
	@XmlElement
	@ApiModelProperty(value = "", allowableValues = "false", dataType = "java.lang.String")
	private String selectable;
.....
.....
}

Don't know whats wrong with my API declaration.

**Comment by fehguy** [comment]
It's `java.lang.String`, and since your field _is_ a string, you can leave that property off.
