### ISSUE TITLE
NullPointerException in ReflectionUtils

### ISSUE THREAD

**Issue by pjfanning** [swagger-api/swagger-core#2028]
java.lang.NullPointerException
	at io.swagger.util.ReflectionUtils.findMethod(ReflectionUtils.java:105)
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:766)
	at io.swagger.jaxrs.Reader.read(Reader.java:298)
	at io.swagger.jaxrs.Reader.read(Reader.java:150)

io.swagger.jaxrs.Reader.parseMethod can passing through a null superclass to ReflectionUtils.findMethod.

**Comment by pjfanning** [comment]
Has been merged
