### ISSUE TITLE
Swagger does work with non-field-method

### ISSUE THREAD

**Issue by paoim** [swagger-api/swagger-core#2031]
Step to re-produce:
1. Create [NonFieldMethodBean] POJO class
class NonFieldMethodBean{
private Integer id;
private String name;

public String sayHello() {
return "Hello";
}
}

2. Use @BeanParam in Resource Class:
        @GET
	@Path("paged")
	@Produces(MediaType.APPLICATION_JSON)
	@Timed
	@UnitOfWork
	@ApiOperation("Get list of the paged pickticket for datatable")
	public Response getRequestData(@BeanParam NonFieldMethodBean object) throws Exception {
		return Response.ok().build();
	}

Here is the detail error:
NFO  [2016-12-13 21:59:30,439] org.eclipse.jetty.util.log: Logging initialized @1186ms
INFO  [2016-12-13 21:59:30,502] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2016-12-13 21:59:30,502] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2016-12-13 21:59:30,505] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: swagger-assets for path /swagger-static/*
INFO  [2016-12-13 21:59:30,636] org.reflections.Reflections: Reflections took 44 ms to scan 2 urls, producing 95 keys and 123 values 
Exception in thread "main" java.lang.IllegalArgumentException: Unrecognized Type: [null]
	at com.fasterxml.jackson.databind.type.TypeFactory._fromAny(TypeFactory.java:1135)
	at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:588)
	at io.swagger.jaxrs.ext.AbstractSwaggerExtension.constructType(AbstractSwaggerExtension.java:53)
	at io.swagger.jaxrs.ext.AbstractSwaggerExtension.shouldIgnoreType(AbstractSwaggerExtension.java:45)
	at io.swagger.jersey.SwaggerJersey2Jaxrs.extractParameters(SwaggerJersey2Jaxrs.java:40)
	at io.swagger.jersey.SwaggerJersey2Jaxrs.extractParameters(SwaggerJersey2Jaxrs.java:82)
	at io.swagger.jaxrs.Reader.getParameters(Reader.java:901)
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:852)
	at io.swagger.jaxrs.Reader.read(Reader.java:293)
	at io.swagger.jaxrs.Reader.read(Reader.java:145)
	at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:223)
	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:204)
	at io.federecio.dropwizard.swagger.SwaggerBundleConfiguration.build(SwaggerBundleConfiguration.java:252)
	at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:61)
	at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:32)
	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
	at io.dropwizard.cli.Cli.run(Cli.java:75)
	at io.dropwizard.Application.run(Application.java:79)

**Comment by fehguy** [comment]
Looks like this is no longer an issue:

https://github.com/swagger-api/swagger-core/pull/2042/commits/911bb58c8a8287ff82fb3aca7947aae894cb9c2a

```
{
  "swagger" : "2.0",
  "paths" : {
    "/paged" : {
      "get" : {
        "summary" : "Get list of the paged pickticket for datatable",
        "description" : "",
        "operationId" : "getRequestData",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/NonFieldMethodBean"
          }
        } ],
        "responses" : {
          "default" : {
            "description" : "successful operation"
          }
        }
      }
    }
  },
  "definitions" : {
    "NonFieldMethodBean" : {
      "type" : "object"
    }
  }
}
```
