### ISSUE TITLE
java.lang.NoSuchMethodError: io.swagger.models.properties.BaseIntegerProperty.getMinimum()Ljava/lang/Double

### ISSUE THREAD

**Issue by zcb22000** [swagger-api/swagger-core#2086]
swagger-core version: 1.5.12
I used swagger-codegen master which packaged version 2.2.2, and use swagger-core version: 1.5.12, but it is failed to parser yaml file.
`
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-codegen</artifactId>
			<version>2.2.2</version>
			<scope>system</scope>
			<systemPath>${basedir}/lib/swagger-codegen-2.2.2-SNAPSHOT.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-core</artifactId>
			<version>1.5.12</version>
		</dependency>
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-parser</artifactId>
			<version>1.0.25</version>
		</dependency>
		<dependency>
			<groupId>com.samskivert</groupId>
			<artifactId>jmustache</artifactId>
			<version>1.13</version>
		</dependency>
		<dependency>
			  <groupId>org.apache.commons</groupId>
			  <artifactId>commons-lang3</artifactId>
			  <version>3.5</version>
		</dependency>`
error stack:
`Exception in thread "main" java.lang.NoSuchMethodError: io.swagger.models.properties.BaseIntegerProperty.getMinimum()Ljava/lang/Double;
	at io.github.swagger2markup.internal.adapter.PropertyAdapter.getMin(PropertyAdapter.java:179)
	at io.github.swagger2markup.internal.component.PropertiesTableComponent.lambda$apply$0(PropertiesTableComponent.java:109)
	at io.github.swagger2markup.internal.component.PropertiesTableComponent$$Lambda$23/369573800.accept(Unknown Source)
	at java.util.TreeMap.forEach(TreeMap.java:1001)
	at io.github.swagger2markup.internal.component.PropertiesTableComponent.apply(PropertiesTableComponent.java:96)
	at io.github.swagger2markup.internal.component.DefinitionComponent.typeSection(DefinitionComponent.java:181)
	at io.github.swagger2markup.internal.component.DefinitionComponent.apply(DefinitionComponent.java:96)
	at io.github.swagger2markup.internal.document.DefinitionsDocument.applyDefinitionComponent(DefinitionsDocument.java:168)
	at io.github.swagger2markup.internal.document.DefinitionsDocument.buildDefinition(DefinitionsDocument.java:146)
	at io.github.swagger2markup.internal.document.DefinitionsDocument.lambda$buildDefinitionsSection$0(DefinitionsDocument.java:110)
	at io.github.swagger2markup.internal.document.DefinitionsDocument$$Lambda$21/1759250827.accept(Unknown Source)
	at java.util.TreeMap.forEach(TreeMap.java:1001)
	at io.github.swagger2markup.internal.document.DefinitionsDocument.buildDefinitionsSection(DefinitionsDocument.java:107)
	at io.github.swagger2markup.internal.document.DefinitionsDocument.apply(DefinitionsDocument.java:94)
	at io.github.swagger2markup.Swagger2MarkupConverter.applyDefinitionsDocument(Swagger2MarkupConverter.java:205)
	at io.github.swagger2markup.Swagger2MarkupConverter.toFolder(Swagger2MarkupConverter.java:186)
	at com.huawei.m2m.ecosystem.codegen.SpringServerGenerator.generateFiles(SpringServerGenerator.java:89)
	at com.huawei.m2m.ecosystem.codegen.SpringServerGenerator.main(SpringServerGenerator.java:49)`

**Comment by pjfanning** [comment]
Could you try the latest swagger2markup jar? They had to make some changes to support swagger 1.5.12. eg https://github.com/Swagger2Markup/swagger2markup/issues/235

**Comment by MichakrawSB** [comment]
Closing this issue as part of our [backlog cleanup effort](https://github.com/swagger-api/swagger-core/issues/5074).  
This issue is outdated and/or inactive for a long time, and we’re not able to revisit it meaningfully.

If this problem is still relevant, please open a new issue and reference this one for context.  
Thank you for your understanding!
