### ISSUE TITLE
java.lang.RuntimeException 	at org.objectweb.asm.MethodVisitor.visitParameter error

### ISSUE THREAD

**Issue by sprba** [swagger-api/swagger-core#2129]
Hi,
While integrating swagger with my RestFul App,I am getting RunTimeException.As per the link:
https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5 

I have added the below in my pom file :
<dependency>
  <groupId>io.swagger</groupId>
  <artifactId>swagger-jersey2-jaxrs</artifactId>
  <version>1.5.0</version>
</dependency>

and in  web.xml,have added :
param-value>io.swagger.jaxrs.listing,***my packages***</param-value>

I have added the annotations into my file too.

Now i am getting error when i deploy the EAR :
com.ibm.ws.ecs.internal.scan.context.impl.ScannerContextImpl scanJAR unable to open input stream for resource org/reflections/scanners/MemberUsageScanner$1.class in archive WEB-INF/lib/reflections-0.9.10.jar
                                 java.lang.RuntimeException
	at org.objectweb.asm.MethodVisitor.visitParameter(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.ibm.ws.ecs.internal.scan.impl.ClassScanner.scanInputStream(ClassScanner.java:149)
	at com.ibm.ws.ecs.internal.scan.impl.ClassScanner.scanInputStream(ClassScanner.java:124)
	at com.ibm.ws.ecs.internal.scan.impl.ClassScanner.scanInputStream(ClassScanner.java:120)
	at com.ibm.ws.ecs.internal.info.impl.ClassInfoManagerImpl.scanClassResource(ClassInfoManagerImpl.java:197)
	at com.ibm.ws.ecs.internal.info.impl.ClassInfoCache.scanClassResource(ClassInfoCache.java:155)
	at com.ibm.ws.ecs.internal.info.impl.ClassInfoCache.resolveClassInfo(ClassInfoCache.java:854)
	at com.ibm.ws.ecs.internal.info.impl.ClassInfoManagerImpl.resolveClassInfo(ClassInfoManagerImpl.java:274)
	at com.ibm.ws.ecs.internal.info.impl.DelayedClassInfo.getClassInfo(DelayedClassInfo.java:245)
	at com.ibm.ws.ecs.internal.info.impl.DelayedClassInfo.getSuperclass(DelayedClassInfo.java:434)
	at com.ibm.ws.ecs.internal.info.impl.NonDelayedClassInfo.getSuperclasses(NonDelayedClassInfo.java:294)
	at com.ibm.ws.ecs.internal.info.impl.NonDelayedClassInfo.getMethodsCollection(NonDelayedClassInfo.java:740)
	at com.ibm.ws.ecs.internal.info.impl.NonDelayedClassInfo.getMethods(NonDelayedClassInfo.java:768)
	at com.ibm.ws.ecs.internal.rules.inheritance.InheritanceRules.applyRules(InheritanceRules.java:77)
	at com.ibm.ws.ecs.internal.rules.AnnotationRulesChain.invoke(AnnotationRulesChain.java:109)
	at com.ibm.ws.ecs.internal.scan.impl.InfoVisitor.visitEndClass(InfoVisitor.java:320)
	at com.ibm.ws.ecs.internal.scan.impl.InfoVisitor.visitEnd(InfoVisitor.java:294)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.ibm.ws.ecs.internal.scan.impl.ClassScanner.scanInputStream(ClassScanner.java:149)
	at com.ibm.ws.ecs.internal.scan.impl.ClassScanner.scanInputStream(ClassScanner.java:124)
	at com.ibm.ws.ecs.internal.scan.impl.ClassScanner.scanInputStream(ClassScanner.java:120)
	at com.ibm.ws.ecs.internal.scan.context.impl.ScannerContextImpl.scanJAR(ScannerContextImpl.java:275)
	at com.ibm.ws.ecs.internal.scan.context.impl.ScannerContextImpl.scanJARs(ScannerContextImpl.java:315)
	at com.ibm.ws.ecs.internal.scan.context.impl.WARScannerContext.scanInternal(WARScannerContext.java:76)
	at com.ibm.ws.ecs.internal.scan.context.impl.ScannerContextImpl.scan(ScannerContextImpl.java:87)
	at com.ibm.ws.ecs.internal.scan.context.impl.ScannerContextImpl.getScannedClasses(ScannerContextImpl.java:70)
	at com.ibm.ws.webcontainer.webapp.WebAppImpl.scanForHandlesTypesClasses(WebAppImpl.java:764)
	at com.ibm.ws.webcontainer.webapp.WebAppImpl.initializeServletContainerInitializers(WebAppImpl.java:605)
	at com.ibm.ws.webcontainer.webapp.WebAppImpl.initialize(WebAppImpl.java:409)
	at com.ibm.ws.webcontainer.webapp.WebGroupImpl.addWebApplication(WebGroupImpl.java:88)
	at com.ibm.ws.webcontainer.VirtualHostImpl.addWebApplication(VirtualHostImpl.java:170)
	at com.ibm.ws.webcontainer.WSWebContainer.addWebApp(WSWebContainer.java:901)
	at com.ibm.ws.webcontainer.WSWebContainer.addWebApplication(WSWebContainer.java:789)
	at com.ibm.ws.webcontainer.component.WebContainerImpl.install(WebContainerImpl.java:427)
	at com.ibm.ws.webcontainer.component.WebContainerImpl.start(WebContainerImpl.java:719)
	at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:1179)
	at com.ibm.ws.runtime.component.DeployedApplicationImpl.__fireDeployedObjectStart(DeployedApplicationImpl.java:1390)
	at com.ibm.ws.runtime.component.DeployedApplicationImpl.fireDeployedObjectStart(DeployedApplicationImpl.java)
	at com.ibm.ws.runtime.component.DeployedModuleImpl.start(DeployedModuleImpl.java:639)
	at com.ibm.ws.runtime.component.DeployedApplicationImpl.start(DeployedApplicationImpl.java:979)
	at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplication(ApplicationMgrImpl.java:778)
	at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplicationDynamically(ApplicationMgrImpl.java:1381)
	at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:2192)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:435)
	at com.ibm.ws.runtime.component.CompositionUnitImpl.start(CompositionUnitImpl.java:123)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:378)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.access$500(CompositionUnitMgrImpl.java:126)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl$1.run(CompositionUnitMgrImpl.java:653)
	at com.ibm.ws.security.auth.ContextManagerImpl.runAs(ContextManagerImpl.java:5396)
	at com.ibm.ws.security.auth.ContextManagerImpl.runAsSystem(ContextManagerImpl.java:5612)
	at com.ibm.ws.security.core.SecurityContext.runAsSystem(SecurityContext.java:255)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.startCompositionUnit(CompositionUnitMgrImpl.java:667)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.startCompositionUnit(CompositionUnitMgrImpl.java:611)
	at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplication(ApplicationMgrImpl.java:1271)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:287)
	at javax.management.modelmbean.RequiredModelMBean$4.run(RequiredModelMBean.java:1263)
	at java.security.AccessController.doPrivileged(AccessController.java:620)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at javax.management.modelmbean.RequiredModelMBean.invokeMethod(RequiredModelMBean.java:1257)
	at javax.management.modelmbean.RequiredModelMBean.invoke(RequiredModelMBean.java:1096)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:831)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:813)
	at com.ibm.ws.management.AdminServiceImpl$1.run(AdminServiceImpl.java:1350)
	at com.ibm.ws.security.util.AccessController.doPrivileged(AccessController.java:118)
	at com.ibm.ws.management.AdminServiceImpl.invoke(AdminServiceImpl.java:1243)
	at com.ibm.ws.management.application.AppManagementImpl._startApplication(AppManagementImpl.java:1482)
	at com.ibm.ws.management.application.AppManagementImpl.startApplication(AppManagementImpl.java:1371)
	at com.ibm.ws.management.application.AppManagementImpl.startApplication(AppManagementImpl.java:1320)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:287)
	at javax.management.modelmbean.RequiredModelMBean$4.run(RequiredModelMBean.java:1263)
	at java.security.AccessController.doPrivileged(AccessController.java:620)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at javax.management.modelmbean.RequiredModelMBean.invokeMethod(RequiredModelMBean.java:1257)
	at javax.management.modelmbean.RequiredModelMBean.invoke(RequiredModelMBean.java:1096)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:831)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:813)
	at com.ibm.ws.management.AdminServiceImpl$1.run(AdminServiceImpl.java:1350)
	at com.ibm.ws.security.util.AccessController.doPrivileged(AccessController.java:118)
	at com.ibm.ws.management.AdminServiceImpl.invoke(AdminServiceImpl.java:1243)
	at com.ibm.ws.management.remote.AdminServiceForwarder.invoke(AdminServiceForwarder.java:346)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1479)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:87)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1320)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1412)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:840)
	at javax.management.remote.rmi._RMIConnectionImpl_Tie.invoke(Unknown Source)
	at javax.management.remote.rmi._RMIConnectionImpl_Tie._invoke(Unknown Source)
	at com.ibm.CORBA.iiop.ServerDelegate.dispatchInvokeHandler(ServerDelegate.java:638)
	at com.ibm.CORBA.iiop.ServerDelegate.dispatch(ServerDelegate.java:508)
	at com.ibm.rmi.iiop.ORB.process(ORB.java:613)
	at com.ibm.CORBA.iiop.ORB.process(ORB.java:1584)
	at com.ibm.rmi.iiop.Connection.doRequestWork(Connection.java:3190)
	at com.ibm.rmi.iiop.Connection.doWork(Connection.java:3051)
	at com.ibm.rmi.iiop.WorkUnitImpl.doWork(WorkUnitImpl.java:64)
	at com.ibm.ejs.oa.pool.PooledThread.run(ThreadPool.java:118)
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1892)

I have added the dependencies too in my pom file :
<dependency>
		    <groupId>org.slf4j</groupId>
		    <artifactId>slf4j-log4j12</artifactId>
		    <version>1.7.21</version>
		</dependency>
		<dependency>
		    <groupId>io.swagger</groupId>
		    <artifactId>swagger-jaxrs</artifactId>
		    <version>1.5.9</version>
		</dependency>
		<dependency>
		    <groupId>org.glassfish.jersey.containers</groupId>
		    <artifactId>jersey-container-servlet-core</artifactId>
		    <version>2.22.2</version>
		</dependency>
		<dependency>
		    <groupId>org.glassfish.jersey.media</groupId>
		    <artifactId>jersey-media-multipart</artifactId>
		    <version>2.22.1</version>
		</dependency>
		<dependency>
		    <groupId>javax.servlet</groupId>
		    <artifactId>servlet-api</artifactId>
		    <version>2.5</version>
		</dependency>
		<dependency>
		    <groupId>org.scalatest</groupId>
		    <artifactId>scalatest_2.10</artifactId>
		    <version>3.0.0</version>
		</dependency>
This is my first time with swagger and i am not sure if there is anything that i have missed.Can someone please look into it and tell me whats the issue?

**Comment by webron** [comment]
Try using the latest version first - 1.5.12.

**Comment by sprba** [comment]
Hi @webron ,I tried using the latest version as you suggested.Its still throwing the same error.Please let me know if there is any other way to get rid of it.
Thanks,
Sushma

**Comment by ivoleitao** [comment]
Hi @webron  I'm also having this issue in the latest version of swagger. The log if full of this exceptions :-S

**Comment by MichakrawSB** [comment]
Closing this issue as part of our [backlog cleanup effort](https://github.com/swagger-api/swagger-core/issues/5074).  
This issue is outdated and/or inactive for a long time, and we’re not able to revisit it meaningfully.

If this problem is still relevant, please open a new issue and reference this one for context.  
Thank you for your understanding!
