### ISSUE TITLE
Method name parsing by swagger-core is case insensitive

### ISSUE THREAD

**Issue by mdhirsch** [swagger-api/swagger-core#2219]
I'm using swagger-ui 2.2.10 to present my REST API. I have a response class like this:

```
public interface Job {

    @CheckForNull
    List<Job> getPredecessors();

    @CheckForNull
    String getPREDECESSORS();
}
```

As you can see, there are two methods that have names that differ only in their use of capitalization, though their signatures are quite different.

When classes are scanned by swagger-core I get an error from the model resolver:

```
Caused by: java.lang.IllegalArgumentException: Conflicting getter definitions for property "predecessors": com.termalabs.ac.rest.Job#getPREDECESSORS(0 params) vs com.termalabs.ac.rest.Job#getPredecessors(0 params)
    at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getGetter(POJOPropertyBuilder.java:244)
    at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getAccessor(POJOPropertyBuilder.java:364)
    at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getPrimaryMember(POJOPropertyBuilder.java:396)
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:306)
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:183)
    at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:100)
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:234)
    at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:183)
    at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:100)
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:159)
    at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:110)
    at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:80)
    at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:58)
    at io.swagger.jaxrs.Reader.parseMethod(Reader.java:896)
    at io.swagger.jaxrs.Reader.read(Reader.java:322)
    at io.swagger.jaxrs.Reader.read(Reader.java:172)
    at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:242)
    at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:221)
    at com.termalabs.server.restapi.JawsSwaggerApplication.<init>(JawsSwaggerApplication.java:40)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:150)
    ... 18 more
```

Apparently jackson can't handle having two different getters with the same spelling but different capitalizations. This is strange to me because both java and Json are case sensitive.

I can find some references to MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES in jackson, but I can't figure out how to use it with Swagger.

Is there a way to make this scanning of my services case sensitive?

Swagger should allow for such different method names, either by default or with a well documented parameter.

**Comment by MichakrawSB** [comment]
Closing this issue as part of our [backlog cleanup effort](https://github.com/swagger-api/swagger-core/issues/5074).  
This issue is outdated and/or inactive for a long time, and we’re not able to revisit it meaningfully.

If this problem is still relevant, please open a new issue and reference this one for context.  
Thank you for your understanding!
