### ISSUE TITLE
Integration with RestEasy 3.x + WildFly - 404 Could not find resource

### ISSUE THREAD

**Issue by imaginalis** [swagger-api/swagger-core#2351]
Hello.
I'm trying to include Swagger into my project. I'm using WildFly (10) server with RestEasy 3.0.11, my resources are EJB-powered and the whole project is building with Ant.

Swagger dependencies are provided by WildFly modules.

The problem is when I'm trying to get swagger.json (via http://localhost:8080/app/api/swagger.json but I've tried other variants of it as well) I've got a 404 response/blank page in the browser and following console output:
`09:40:49,893 WARN  [org.jboss.resteasy.core.ExceptionHandler] (Log4jLogger.java:135) failed to execute: javax.ws.rs.NotFoundException: Could not find resource for full path: http://localhost:8080/app/api/swagger.json
at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:112)
at org.jboss.resteasy.core.registry.RootNode.match(RootNode.java:43)
at org.jboss.resteasy.core.registry.RootClassNode.match(RootClassNode.java:48)
at org.jboss.resteasy.core.ResourceMethodRegistry.getResourceInvoker(ResourceMethodRegistry.java:444)
at org.jboss.resteasy.core.SynchronousDispatcher.getInvoker(SynchronousDispatcher.java:234)
at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:171)
at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220)
at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86)
at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:72)
at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:282)
at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:261)
at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:80)
at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:172)
at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:774)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)`

The web.xml configuration is as follows:

<?xml version="1.0" encoding="ISO-8859-1"?>

<web-app>

    <display-name>app</display-name>
    <description>app</description>

    <context-param>
        <param-name>resteasy.scan</param-name>
        <param-value>true</param-value>
    </context-param>

    <servlet-mapping>
        <servlet-name>javax.ws.rs.core.Application</servlet-name>
        <url-pattern>*.json</url-pattern>
    </servlet-mapping>

    <servlet>
        <servlet-name>SwaggerServlet</servlet-name>
        <servlet-class>my.example.app.examples.web.SwaggerServlet</servlet-class>
        <load-on-startup>2</load-on-startup>
    </servlet> 
</web-app>

And here's a SwaggerServlet mentioned above: 

    import io.swagger.config.ScannerFactory;
    import io.swagger.jaxrs.config.BeanConfig;
    import io.swagger.jaxrs.config.DefaultJaxrsScanner;
    import io.swagger.jaxrs.config.SwaggerContextService;

    import javax.servlet.ServletConfig;
    import javax.servlet.ServletException;
    import javax.servlet.http.HttpServlet;

    import org.jboss.logging.Logger;

    public class SwaggerServlet extends HttpServlet {
        private static Logger log = Logger.getLogger(SwaggerServlet.class);

        @Override
        public void init(ServletConfig config) throws ServletException {
            try {
                super.init(config);
                BeanConfig beanConfig = new BeanConfig();
                beanConfig.setVersion("1.0.0");
                beanConfig.setSchemes(new String[] { "http" });
                beanConfig.setHost("localhost:8080");
                beanConfig.setBasePath("/api");
    beanConfig.setResourcePackage("io.swagger.resources,io.swagger.jaxrs.listing,my.example.app.exampleresources");
                beanConfig.setScan(true);
                log.info("Swagger servlet has been initialized");
            } catch (ServletException e) {
                log.error(e);
            }

      }
    }

And while starting my application the servlet seems to initialize:
`09:40:33,809 INFO  [my.example.app.examples.web.SwaggerServlet] (SwaggerServlet.java:40) Swagger servlet has been initialized`

My web resource is working and responding properly (on http://localhost:8080/app/example/listOfExampleResources.json). The ExampleModel class is just a POJO:

    @Api(value = "/app")
    @Stateless
    @Path("/app")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    public class ExampleController {

    @GET
    @Path("/example/listOfExampleResources.json")
    @ApiOperation(value = "Get list of example resources", 
        notes = "Note test", 
        response = ExampleModel.class,
        responseContainer = "list"
    )
    @Produces("application/json")
    public List<ExampleModel> getList() {
        List<ExampleModel> list = new ArrayList<ExampleModel>();
        ExampleModel example = new ExampleModel();
        example.setName("Hello");
        list.add(example);
        return list;
        }
    }

I've tried other parameters and configuration approaches such as configuration via custom Application class, defining servlet inside web.xml, manual resources providing. I was replacing RestEasy with older version (3.0.4) as well - but all in all I'm still getting 404.

Do you have any idea how can I get swagger.json resource?

Thanks for your time.

**Comment by red61wjt** [comment]
I have also spent quite a bit of time banging my head off a desk with this one. I think I possibly managed something when overriding getClasses in Application, but this is not really workable going forward

**Comment by jbarrett732** [comment]
I have a very simple API that was working great with resteasy 2.x, but have failed miserably trying to get any possible solution working with resteasy 3.x. I am amazed that there has not been more interest or documentation on this topic. Somebody please help!

**Comment by red61wjt** [comment]
I have it working with resteasy 3.x by using the BeanConfig

@ApplicationPath("/rest/")
public class JaxRsActivator extends Application {

	public JaxRsActivator() {
		BeanConfig beanConfig = new BeanConfig();
		beanConfig.setVersion("v1");
		beanConfig.setTitle("My app");
		beanConfig.setBasePath("/example/rest/");
		beanConfig.setScan(true);
	}
}

And 

        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jaxrs</artifactId>
            <version>1.5.8</version>
        </dependency>

**Comment by LafsarColdwalker** [comment]
I had a similar issue on WildFly 10 and RestEasy 3.0.16.
I used the BeanConfig as suggested by @red61wjt but I had to set also the ResourcePackage into the BeanConfig. It doesn't work without ResourcePackage.
My configuration is the follow:

`@ApplicationPath("/api")
public class JaxRsActivator extends Application {

    public JaxRsActivator() {
        BeanConfig beanConfig = new BeanConfig();
        beanConfig.setVersion("v1");
        beanConfig.setDescription("My Description");
        beanConfig.setTitle("My Title");
        beanConfig.setBasePath("/api");
        beanConfig.setResourcePackage("my.package.with.rest.controllers");
        beanConfig.setScan(true);
    }

}`

In the pom I have:

`      <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-jaxrs</artifactId>
            <version>1.5.19</version>
        </dependency>`

I hope it could help you ;)

**Comment by fjakop** [comment]
Maybe not 100% correct thread, but using configuration from https://github.com/swagger-api/swagger-core/issues/2351#issuecomment-387078313 on JBoss EAP 7 gives
`java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;`

Has anyone similar problems?

**Comment by red61wjt** [comment]
You are using the wrong version of Guava, check the version that is required by swagger is the version being bundled into your deployment or it might be that swagger is forcing an upgrade of guava that other parts of your codebase can't handle, you are not including enough of the stack to tell

**Comment by fjakop** [comment]
Well, guava 19 is bundled with JBoss 7.0.9 EAP, but even including version 23 in the deployment and excluding the module named "com.google.guava" via _jboss-deployment-structure.xml_ leads to the same error.

```
[2018-09-24 10:50:11,588] Artifact foo:war exploded: Artifact is being deployed, please wait...
10:50:16,412 WARN  [org.hibernate.orm.deprecation] (ServerService Thread Pool -- 275) HHH90000014: Found use of deprecated [org.hibernate.id.SequenceIdentityGenerator] sequence-based id generator; use org.hibernate.id.enhanced.SequenceStyleGenerator instead.  See Hibernate Domain Model Mapping Guide for details.
10:50:16,413 WARN  [org.hibernate.orm.deprecation] (ServerService Thread Pool -- 275) HHH90000014: Found use of deprecated [org.hibernate.id.SequenceIdentityGenerator] sequence-based id generator; use org.hibernate.id.enhanced.SequenceStyleGenerator instead.  See Hibernate Domain Model Mapping Guide for details.
10:50:21,796 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 279) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./foo: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./foo: com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85) [wildfly-undertow-7.0.9.GA-redhat-3.jar:7.0.9.GA-redhat-3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_144]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [rt.jar:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [rt.jar:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_144]
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.jboss.weld.util.cache.LoadingCacheUtils.getCacheValue(LoadingCacheUtils.java:49)
	at org.jboss.weld.util.cache.LoadingCacheUtils.getCastCacheValue(LoadingCacheUtils.java:74)
	at org.jboss.weld.bean.proxy.ClientProxyProvider.getClientProxy(ClientProxyProvider.java:233)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:736)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:765)
	at org.jboss.weld.util.ForwardingBeanManager.getReference(ForwardingBeanManager.java:61)
	at org.jboss.weld.bean.builtin.BeanManagerProxy.getReference(BeanManagerProxy.java:85)
	at org.jboss.resteasy.cdi.CdiConstructorInjector.construct(CdiConstructorInjector.java:65)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2280)
	at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:304)
	at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:245)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:113)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78) [wildfly-undertow-7.0.9.GA-redhat-3.jar:7.0.9.GA-redhat-3]
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:239)
	at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:133)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:527)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:101) [wildfly-undertow-7.0.9.GA-redhat-3.jar:7.0.9.GA-redhat-3]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82) [wildfly-undertow-7.0.9.GA-redhat-3.jar:7.0.9.GA-redhat-3]
	... 7 more
Caused by: java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:380)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:276)
	at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:240)
	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:221)
	at com.foo.bar.rs.JaxRsActivator.<init>(JaxRsActivator.java:18)
	at com.foo.bar.rs.JaxRsActivator$Proxy$_$$_WeldClientProxy.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.8.0_144]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [rt.jar:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [rt.jar:1.8.0_144]
	at java.lang.Class.newInstance(Class.java:442) [rt.jar:1.8.0_144]
	at org.jboss.weld.bean.proxy.DefaultProxyInstantiator.newInstance(DefaultProxyInstantiator.java:43)
	at org.jboss.weld.bean.proxy.ProxyFactory.run(ProxyFactory.java:332)
	at org.jboss.weld.bean.proxy.ProxyFactory.create(ProxyFactory.java:324)
	at org.jboss.weld.bean.proxy.ClientProxyFactory.create(ClientProxyFactory.java:83)
	at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:209)
	at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:199)
	at org.jboss.weld.bean.proxy.ClientProxyProvider.access$100(ClientProxyProvider.java:47)
	at org.jboss.weld.bean.proxy.ClientProxyProvider$CreateClientProxy.load(ClientProxyProvider.java:55)
	at org.jboss.weld.bean.proxy.ClientProxyProvider$CreateClientProxy.load(ClientProxyProvider.java:51)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 31 more

10:50:21,817 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 11) WFLYCTL0013: Operation ("deploy") fehlgeschlagen - Adresse: ([("deployment" => "foo-master-SNAPSHOT")]) - Fehlerbeschreibung: {"WFLYCTL0080: Fehlgeschlagene Dienste" => {"jboss.undertow.deployment.default-server.default-host./foo" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./foo: com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
    Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
    Caused by: java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;"}}
10:50:21,818 ERROR [org.jboss.as.server] (management-handler-thread - 11) WFLYSRV0021: Deploy von Deployment "foo-master-SNAPSHOT.war" wurde mit folgender Fehlermeldung zurückgesetzt: 
{"WFLYCTL0080: Fehlgeschlagene Dienste" => {"jboss.undertow.deployment.default-server.default-host./foo" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./foo: com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
    Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
    Caused by: java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;"}} 
[2018-09-24 10:50:22,084] Artifact foo:war exploded: Error during artifact deployment. See server log for details.
[2018-09-24 10:50:22,084] Artifact foo:war exploded: java.lang.Exception: {"WFLYCTL0080: Fehlgeschlagene Dienste" => {"jboss.undertow.deployment.default-server.default-host./foo" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./foo: com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
    Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
    Caused by: java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;"}}
```
