### ISSUE TITLE
java.lang.NullPointerException at io.swagger.jaxrs.config.BeanConfig.classes

### ISSUE THREAD

**Issue by stemar87** [swagger-api/swagger-core#2418]
Hi everybody,
as the title suggests I experience a NPE while using `BeanConfig` for generating Swagger documentation for a Jersey project I'm developing.
**Notice**: I browsed through both open/closed issues but found no solution in my specific setting.

In particular, my setting and workflow followed are as follows (_please, do not hesitate to ask for further clarification if I am missing anything_):

- I followed the documentation at [https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5](https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5)

  - but, I am using Gradle, not Maven thus my only Gradle dependency is 

> compile 'io.swagger:swagger-jersey2-jaxrs:1.5.16'

 - also, I do not have any `web.xml` nor `Application` subclass
   - nevertheless, I am using Jersey `ResourceConfig`, which should offer the same functionalities

 - My only (atm) REST resource is annotated with (dummy fields for hiding details)

```java
@Singleton
@javax.ws.rs.Path("foo")
@Api(value = "foo")
@Produces({ "application/json","application/xml" })
@SwaggerDefinition(info = @Info(description = "A foo service", version = "0.0.1", title = "The Foo Service",
contact = @Contact(name = "Stefano Mariani", email = "john.doe@acme.inc", url = "https://fake.address.com/"),
license = @License(name = "Apache 2.0", url = "http://www.apache.org/licenses/LICENSE-2.0")),
consumes = {"application/json", "application/xml" },
produces = { "application/json", "application/xml" },
schemes = { SwaggerDefinition.Scheme.HTTPS })
````
and lives in package `fake.package.path`

 - To start my Grizzly 2 embedded server I use

```java
BeanConfig beanConfig = new BeanConfig();
beanConfig.setHost(this.adaptedIp + ":" + this.endpointTcp);
beanConfig.setBasePath("/api-docs");
beanConfig.setResourcePackage("fake.package.path");
beanConfig.setScan(true);
final ResourceConfig config = new ResourceConfig(this.resourceClazz,
io.swagger.jaxrs.listing.ApiListingResource.class, io.swagger.jaxrs.listing.SwaggerSerializers.class)
.packages("org.glassfish.jersey.examples.jackson").register(JacksonFeature.class)
.register(MultiPartFeature.class);
this.server = GrizzlyHttpServerFactory.createHttpServer(baseUri, config);
this.server.start();
````

In the above configuration I get the mentioned exception.

FYI, I tried a few changes based on open/closed issues found on Github issue tracker for Swagger core:
 - Adding before BeanConfig set up the following code

```java
ReflectiveJaxrsScanner scanner = new ReflectiveJaxrsScanner();
scanner.setResourcePackage("eu.connecare.cdss.hadrian.rest");
ScannerFactory.setScanner(scanner);
````

based on [https://github.com/swagger-api/swagger-core/issues/927](https://github.com/swagger-api/swagger-core/issues/927)

 - Wrapping the server in a `ServletContainer`

```java
ServletContainer sc = new ServletContainer(config);
this.server = GrizzlyWebContainerFactory.create(baseUri, sc, null, null);
````

based on [https://stackoverflow.com/questions/33681371/swagger-documentation-with-jax-rs-jersey-2-and-grizzly](https://stackoverflow.com/questions/33681371/swagger-documentation-with-jax-rs-jersey-2-and-grizzly)

but none of them worked.

Also fyi, it is worth mentioning that besides the exception stack trace I get no log messages whatsoever indicating that Swagger is doing anything.
BUT, if I add the following dependencies to my Gradle build script

> compile 'io.swagger:swagger-annotations:1.5.16'
> compile 'io.swagger:swagger-codegen:2.2.3'

I get the following log line (without changing anything else)

> INFO org.reflections.Reflections - Reflections took 92 ms to scan 1 urls, producing 65 keys and 77 values

Any idea of what I am doing wrong?

 :)

**Comment by vanta** [comment]
How about attaching stacktrace...?

**Comment by stemar87** [comment]
Sorry, did the report in a rush on the train and forgot the most important thing :/
Here it is, although I'm afraid it isn't of much help...

FYI omitted trace is simply the call to `beanConfig.setScan(true);` in my implementation.

``` 
Exception in thread "main" java.lang.NullPointerException
	at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:304)
	at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:240)
	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:221)
```
