### ISSUE TITLE
`java.lang.ClassNotFoundException: org.reflections.Configuration` using io.swagger.core.v3:swagger-jaxrs2:2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by stiancognite** [swagger-api/swagger-core#2520]
I had this problem with `io.swagger:swagger-jaxrs2:2.0.0-rc2` as well. If I don't have a dependency on `org.reflections:reflections:0.9.11`, I get this runtime error when trying to fetch `openapi.json`:

```
 java.lang.NoClassDefFoundError: org/reflections/Configuration
	at io.swagger.v3.jaxrs2.integration.JaxrsOpenApiContext.buildScanner(JaxrsOpenApiContext.java:51) ~[swagger-jaxrs2-2.0.0-20171111.113024-9.jar:2.0.0-SNAPSHOT]
	at io.swagger.v3.oas.integration.GenericOpenApiContext.init(GenericOpenApiContext.java:273) ~[swagger-integration-2.0.0-20171111.113008-9.jar:2.0.0-SNAPSHOT]
	at io.swagger.v3.oas.integration.GenericOpenApiContext.init(GenericOpenApiContext.java:22) ~[swagger-integration-2.0.0-20171111.113008-9.jar:2.0.0-SNAPSHOT]
	at io.swagger.v3.jaxrs2.integration.JaxrsOpenApiContextBuilder.buildContext(JaxrsOpenApiContextBuilder.java:43) ~[swagger-jaxrs2-2.0.0-20171111.113024-9.jar:2.0.0-SNAPSHOT]
	at io.swagger.v3.jaxrs2.integration.resources.BaseOpenApiResource.getOpenApi(BaseOpenApiResource.java:48) ~[swagger-jaxrs2-2.0.0-20171111.113024-9.jar:2.0.0-SNAPSHOT]
	at io.swagger.v3.jaxrs2.integration.resources.OpenApiResource.getOpenApi(OpenApiResource.java:32) ~[swagger-jaxrs2-2.0.0-20171111.113024-9.jar:2.0.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) [jersey-container-servlet-core-2.25.1.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) [jersey-container-servlet-core-2.25.1.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) [jersey-container-servlet-core-2.25.1.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) [jersey-container-servlet-core-2.25.1.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) [jersey-container-servlet-core-2.25.1.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812) [jetty-servlet-9.2.21.v20170120.jar:9.2.21.v20170120]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [jetty-servlet-9.2.21.v20170120.jar:9.2.21.v20170120]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) [shiro-web-1.3.2.jar:1.3.2]
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) [shiro-web-1.3.2.jar:1.3.2]
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.3.2.jar:1.3.2]
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.3.2.jar:1.3.2]
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383) [shiro-core-1.3.2.jar:1.3.2]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) [shiro-web-1.3.2.jar:1.3.2]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.3.2.jar:1.3.2]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.21.v20170120.jar:9.2.21.v20170120]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.21.v20170120.jar:9.2.21.v20170120]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.21.v20170120.jar:9.2.21.v20170120]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.21.v20170120.jar:9.2.21.v20170120]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.21.v20170120.jar:9.2.21.v20170120]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.21.v20170120.jar:9.2.21.v20170120]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.21.v20170120.jar:9.2.21.v20170120]
	at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.21.v20170120.jar:9.2.21.v20170120]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311) [jetty-server-9.2.21.v20170120.jar:9.2.21.v20170120]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258) [jetty-server-9.2.21.v20170120.jar:9.2.21.v20170120]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544) [jetty-io-9.2.21.v20170120.jar:9.2.21.v20170120]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.21.v20170120.jar:9.2.21.v20170120]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.21.v20170120.jar:9.2.21.v20170120]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: org.reflections.Configuration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	... 55 more
```

**Comment by frantuma** [comment]
mm.. this is weird, reflection dep should be correctly referenced; are you getting the same issue with latest snapshot? also can you in case share your declared deps in project giving error?

**Comment by stiancognite** [comment]
I do believe I'm using the latest snapshot. `mvn dependency:tree` gives me the following (after removing one internal library and sorting):
```
[INFO]    ch.vorburger.mariaDB4j:mariaDB4j-core:jar:2.2.3-1:test
[INFO]    ch.vorburger.mariaDB4j:mariaDB4j-db-linux64:jar:5.7.19:test
[INFO]    ch.vorburger.mariaDB4j:mariaDB4j-db-mac64:jar:5.7.19:test
[INFO]    ch.vorburger.mariaDB4j:mariaDB4j-db-win32:jar:10.2.7:test
[INFO]    com.fasterxml.jackson.core:jackson-annotations:jar:2.8.10:compile
[INFO]    com.fasterxml.jackson.core:jackson-core:jar:2.8.10:compile
[INFO]    com.fasterxml.jackson.core:jackson-databind:jar:2.8.10:compile
[INFO]    com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.1:compile
[INFO]    com.github.kstyrc:embedded-redis:jar:0.6:test
[INFO]    com.github.stephenc.findbugs:findbugs-annotations:jar:1.3.9-1:compile
[INFO]    com.google.api:api-common:jar:1.1.0:compile
[INFO]    com.google.api-client:google-api-client:jar:1.23.0:compile
[INFO]    com.google.api:gax-grpc:jar:0.26.0:compile
[INFO]    com.google.api:gax:jar:1.9.0:compile
[INFO]    com.google.api.grpc:grpc-google-cloud-pubsub-v1:jar:0.1.21:compile
[INFO]    com.google.api.grpc:grpc-google-common-protos:jar:0.1.9:compile
[INFO]    com.google.api.grpc:proto-google-cloud-pubsub-v1:jar:0.1.21:compile
[INFO]    com.google.api.grpc:proto-google-common-protos:jar:0.1.21:compile
[INFO]    com.google.api.grpc:proto-google-iam-v1:jar:0.1.21:compile
[INFO]    com.google.apis:google-api-services-storage:jar:v1-rev115-1.23.0:compile
[INFO]    com.google.auth:google-auth-library-appengine:jar:0.7.0:compile
[INFO]    com.google.auth:google-auth-library-credentials:jar:0.8.0:compile
[INFO]    com.google.auth:google-auth-library-oauth2-http:jar:0.8.0:compile
[INFO]    com.google.auto.value:auto-value:jar:1.2:compile
[INFO]    com.google.cloud.bigtable:bigtable-client-core:jar:1.0.0-pre4:compile
[INFO]    com.google.cloud.bigtable:bigtable-hbase-1.x:jar:1.0.0-pre4:compile
[INFO]    com.google.cloud.bigtable:bigtable-hbase:jar:1.0.0-pre4:compile
[INFO]    com.google.cloud.bigtable:bigtable-protos:jar:1.0.0-pre4:compile
[INFO]    com.google.cloud:google-cloud-core-grpc:jar:1.8.0:compile
[INFO]    com.google.cloud:google-cloud-core-http:jar:1.8.0:compile
[INFO]    com.google.cloud:google-cloud-core:jar:1.8.0:compile
[INFO]    com.google.cloud:google-cloud-pubsub:jar:0.26.0-beta:compile
[INFO]    com.google.cloud:google-cloud-storage:jar:1.8.0:compile
[INFO]    com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO]    com.google.code.gson:gson:jar:2.7:compile
[INFO]    com.google.errorprone:error_prone_annotations:jar:2.0.19:compile
[INFO]    com.google.guava:guava:jar:21.0:compile
[INFO]    com.google.http-client:google-http-client-appengine:jar:1.22.0:compile
[INFO]    com.google.http-client:google-http-client-jackson2:jar:1.23.0:compile
[INFO]    com.google.http-client:google-http-client-jackson:jar:1.22.0:compile
[INFO]    com.google.http-client:google-http-client:jar:1.23.0:compile
[INFO]    com.google.instrumentation:instrumentation-api:jar:0.4.3:compile
[INFO]    com.google.oauth-client:google-oauth-client:jar:1.23.0:compile
[INFO]    com.google.protobuf:protobuf-java:jar:3.4.0:compile
[INFO]    com.google.protobuf:protobuf-java-util:jar:3.4.0:compile
[INFO]    commons-beanutils:commons-beanutils:jar:1.9.3:compile
[INFO]    commons-cli:commons-cli:jar:1.4:compile
[INFO]    commons-codec:commons-codec:jar:1.9:compile
[INFO]    commons-collections:commons-collections:jar:3.2.2:compile
[INFO]    commons-io:commons-io:jar:2.5:compile
[INFO]    commons-logging:commons-logging:jar:1.2:compile
[INFO]    com.opencsv:opencsv:jar:3.3:compile
[INFO]    com.sendgrid:java-http-client:jar:4.1.0:compile
[INFO]    com.sendgrid:sendgrid-java:jar:4.1.0:compile
[INFO]    com.squareup.okhttp3:okhttp:jar:3.8.1:compile
[INFO]    com.squareup.okio:okio:jar:1.13.0:compile
[INFO]    io.dropwizard.metrics:metrics-core:jar:3.1.2:compile
[INFO]    io.grpc:grpc-auth:jar:1.7.0:compile
[INFO]    io.grpc:grpc-context:jar:1.7.0:compile
[INFO]    io.grpc:grpc-core:jar:1.7.0:compile
[INFO]    io.grpc:grpc-netty:jar:1.7.0:compile
[INFO]    io.grpc:grpc-protobuf:jar:1.7.0:compile
[INFO]    io.grpc:grpc-protobuf-lite:jar:1.7.0:compile
[INFO]    io.grpc:grpc-stub:jar:1.7.0:compile
[INFO]    io.netty:netty-buffer:jar:4.1.16.Final:compile
[INFO]    io.netty:netty-codec-http2:jar:4.1.16.Final:compile
[INFO]    io.netty:netty-codec-http:jar:4.1.16.Final:compile
[INFO]    io.netty:netty-codec:jar:4.1.16.Final:compile
[INFO]    io.netty:netty-codec-socks:jar:4.1.16.Final:compile
[INFO]    io.netty:netty-common:jar:4.1.16.Final:compile
[INFO]    io.netty:netty-handler:jar:4.1.16.Final:compile
[INFO]    io.netty:netty-handler-proxy:jar:4.1.16.Final:compile
[INFO]    io.netty:netty-resolver:jar:4.1.16.Final:compile
[INFO]    io.netty:netty-tcnative-boringssl-static:jar:2.0.6.Final:compile
[INFO]    io.netty:netty-transport:jar:4.1.16.Final:compile
[INFO]    io.opencensus:opencensus-api:jar:0.7.0:compile
[INFO]    io.opencensus:opencensus-contrib-grpc-util:jar:0.7.0:compile
[INFO]    io.prometheus:simpleclient_common:jar:0.0.26:compile
[INFO]    io.prometheus:simpleclient_hotspot:jar:0.0.26:compile
[INFO]    io.prometheus:simpleclient:jar:0.0.26:compile
[INFO]    io.prometheus:simpleclient_servlet:jar:0.0.26:compile
[INFO]    io.swagger.core.v3:swagger-annotations:jar:2.0.0-SNAPSHOT:compile
[INFO]    io.swagger.core.v3:swagger-core:jar:2.0.0-SNAPSHOT:compile
[INFO]    io.swagger.core.v3:swagger-integration:jar:2.0.0-SNAPSHOT:compile
[INFO]    io.swagger.core.v3:swagger-jaxrs2:jar:2.0.0-SNAPSHOT:compile
[INFO]    io.swagger.core.v3:swagger-models:jar:2.0.0-SNAPSHOT:compile
[INFO]    io.zipkin.brave:brave-instrumentation-http:jar:4.7.1:compile
[INFO]    io.zipkin.brave:brave-instrumentation-jaxrs2:jar:4.7.1:compile
[INFO]    io.zipkin.brave:brave-instrumentation-p6spy:jar:4.7.1:compile
[INFO]    io.zipkin.brave:brave:jar:4.7.1:compile
[INFO]    io.zipkin.java:zipkin:jar:2.0.0:compile
[INFO]    io.zipkin.reporter:zipkin-reporter:jar:1.1.0:compile
[INFO]    io.zipkin.reporter:zipkin-sender-okhttp3:jar:1.1.0:compile
[INFO]    io.zipkin.zipkin2:zipkin:jar:2.0.0:compile
[INFO]    javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO]    javax.inject:javax.inject:jar:1:compile
[INFO]    javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO]    javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO]    javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO]    joda-time:joda-time:jar:2.9.9:compile
[INFO]    junit:junit:jar:4.12:test
[INFO]    mysql:mysql-connector-java:jar:5.1.6:compile
[INFO]    one.util:streamex:jar:0.6.5:compile
[INFO]    org.apache.commons:commons-collections4:jar:4.1:test
[INFO]    org.apache.commons:commons-dbcp2:jar:2.1.1:compile
[INFO]    org.apache.commons:commons-exec:jar:1.3:test
[INFO]    org.apache.commons:commons-lang3:jar:3.5:compile
[INFO]    org.apache.commons:commons-pool2:jar:2.4.2:compile
[INFO]    org.apache.hbase:hbase-shaded-client:jar:1.3.1:compile
[INFO]    org.apache.htrace:htrace-core:jar:3.1.0-incubating:compile
[INFO]    org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO]    org.apache.httpcomponents:httpcore:jar:4.4.4:compile
[INFO]    org.apache.logging.log4j:log4j-api:jar:2.8.2:compile
[INFO]    org.apache.logging.log4j:log4j-core:jar:2.8.2:compile
[INFO]    org.apache.logging.log4j:log4j-slf4j-impl:jar:2.8.2:compile
[INFO]    org.apache.logging.log4j:log4j-web:jar:2.8.2:compile
[INFO]    org.apache.shiro:shiro-core:jar:1.3.2:compile
[INFO]    org.apache.shiro:shiro-web:jar:1.3.2:compile
[INFO]    org.codehaus.jackson:jackson-core-asl:jar:1.9.11:compile
[INFO]    org.eclipse.jetty:jetty-continuation:jar:9.2.14.v20151106:compile
[INFO]    org.eclipse.jetty:jetty-http:jar:9.2.21.v20170120:compile
[INFO]    org.eclipse.jetty:jetty-io:jar:9.2.21.v20170120:compile
[INFO]    org.eclipse.jetty:jetty-security:jar:9.2.21.v20170120:compile
[INFO]    org.eclipse.jetty:jetty-server:jar:9.2.21.v20170120:compile
[INFO]    org.eclipse.jetty:jetty-servlet:jar:9.2.21.v20170120:compile
[INFO]    org.eclipse.jetty:jetty-util:jar:9.2.21.v20170120:compile
[INFO]    org.glassfish.hk2.external:aopalliance-repackaged:jar:2.5.0-b32:compile
[INFO]    org.glassfish.hk2:hk2-api:jar:2.5.0-b32:compile
[INFO]    org.glassfish.hk2:hk2-locator:jar:2.5.0-b32:compile
[INFO]    org.glassfish.hk2:hk2-utils:jar:2.5.0-b32:compile
[INFO]    org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO]    org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.25.1:compile
[INFO]    org.glassfish.jersey.containers:jersey-container-jetty-http:jar:2.25.1:compile
[INFO]    org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.25.1:compile
[INFO]    org.glassfish.jersey.containers:jersey-container-servlet:jar:2.25.1:compile
[INFO]    org.glassfish.jersey.core:jersey-client:jar:2.25.1:compile
[INFO]    org.glassfish.jersey.core:jersey-common:jar:2.25.1:compile
[INFO]    org.glassfish.jersey.core:jersey-server:jar:2.25.1:compile
[INFO]    org.glassfish.jersey.media:jersey-media-jaxb:jar:2.25.1:compile
[INFO]    org.glassfish.jersey.test-framework:jersey-test-framework-core:jar:2.25.1:compile
[INFO]    org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-jetty:jar:2.25.1:compile
[INFO]    org.hamcrest:hamcrest-core:jar:1.3:test
[INFO]    org.hamcrest:hamcrest-library:jar:1.3:test
[INFO]    org.javassist:javassist:jar:3.21.0-GA:compile
[INFO]    org.jooq:jooq:jar:3.9.3:compile
[INFO]    org.json:json:jar:20160810:compile
[INFO]    org.mockito:mockito-core:jar:1.10.19:test
[INFO]    org.objenesis:objenesis:jar:2.4:test
[INFO]    org.powermock:powermock-api-mockito-common:jar:1.6.6:test
[INFO]    org.powermock:powermock-api-mockito:jar:1.6.6:test
[INFO]    org.powermock:powermock-api-support:jar:1.6.6:test
[INFO]    org.powermock:powermock-core:jar:1.6.6:test
[INFO]    org.powermock:powermock-module-junit4-common:jar:1.6.6:test
[INFO]    org.powermock:powermock-module-junit4:jar:1.6.6:test
[INFO]    org.powermock:powermock-reflect:jar:1.6.6:test
[INFO]    org.secnod.shiro:shiro-jersey:jar:0.2.0:compile
[INFO]    org.slf4j:jul-to-slf4j:jar:1.7.25:compile
[INFO]    org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO]    org.springframework:spring-core:jar:4.3.6.RELEASE:test
[INFO]    org.threeten:threetenbp:jar:1.3.3:compile
[INFO]    org.yaml:snakeyaml:jar:1.18:compile
[INFO]    p6spy:p6spy:jar:3.3.0:compile
[INFO]    redis.clients:jedis:jar:2.9.0:compile
```

+ reflections when I add that.

**Comment by frantuma** [comment]
Not really sure why you're getting this; `org.reflections` should be picked as transitive dep (from `swagger-jaxrs2`), with correct version; possibly it would help if you could share a ` mvn dependency:tree -Dverbose` output, full stack trace, and project POM. Also it can possibly help building with `-U`, please give that a try

**Comment by stiancognite** [comment]
We have a `<scope>test</scope>` dependency on `org.reflections`, which seems to stop swaggers import of the library. This is pat of the `mvn dependency:tree -Dverbose` output:
```
[INFO] +- io.swagger.core.v3:swagger-jaxrs2:jar:2.0.0-SNAPSHOT:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.1:compile
[INFO] |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.9.1:compile - version managed from 2.9.0; omitted for duplicate)
[INFO] |  |  \- (com.fasterxml.jackson.core:jackson-core:jar:2.9.1:compile - version managed from 2.1.3; omitted for duplicate)
[INFO] |  +- (org.reflections:reflections:jar:0.9.11:compile - omitted for duplicate)
--
--
[INFO] |  +- io.swagger.core.v3:swagger-annotations:jar:2.0.0-SNAPSHOT:compile
[INFO] |  \- io.swagger.core.v3:swagger-integration:jar:2.0.0-SNAPSHOT:compile
[INFO] |     +- (org.reflections:reflections:jar:0.9.11:compile - omitted for duplicate)
--
--
[INFO] +- org.reflections:reflections:jar:0.9.11:test (scope not updated to compile)
[INFO] |  +- (com.google.guava:guava:jar:23.0:test - version managed from 20.0; omitted for duplicate)
[INFO] |  \- (org.javassist:javassist:jar:3.21.0-GA:test - version managed from 3.20.0-GA; omitted for duplicate)
```

Do you think that's what's wrong? That our test scoped dependency on reflections stops swaggers dependency?

**Comment by frantuma** [comment]
I guess this is a bit out of scope of swagger-core, but I suspect this is caused by https://issues.apache.org/jira/browse/MNG-5739 or similar, it should work ok just by changing the scope of your direct dep to `compile`

**Comment by stiancognite** [comment]
Thank you! :)
