### ISSUE TITLE
Generating documentation causes ClassNotFound from @ApiImplicitParam

### ISSUE THREAD

**Issue by langecode** [swagger-api/swagger-core#2556]
Generating documentation from classes containing the `@ApiImplicitParam` annotation generates huge stack traces if the annotation does not contain either `dataTypeClass` or `dataType` parameter.
 
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           | feature request
| Which Swagger-Core version?       |1.5.15
| Which Java version?               |9 build 181

When neither the `dataTypeClass` nor the `dataType` property of the the annotation is set an large exception stack trace is printed because the code tries to do classloading of the empty string (the default value for `dataType`). The type is defaulted to `string` anyway so maybe the default value in for `dataType` in the annotation might be set to string to avoid the large stack trace.

This can easily be reproduced generating documentation from a class that contains an `@ApiImplicitParam` annotation with no value set for either `dataTypeClass` nor `dataType`.

```
Failed to resolve '' into class
java.lang.ClassNotFoundException:
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at io.swagger.util.ReflectionUtils.loadClassByName(ReflectionUtils.java:49)
        at io.swagger.util.ReflectionUtils.typeFromString(ReflectionUtils.java:31)
        at io.swagger.jaxrs.Reader.readImplicitParam(Reader.java:475)
        at io.swagger.jaxrs.Reader.processImplicitParams(Reader.java:444)
        at io.swagger.jaxrs.Reader.readImplicitParameters(Reader.java:437)
        at io.swagger.jaxrs.Reader.read(Reader.java:425)
        at io.swagger.jaxrs.Reader.read(Reader.java:172)
        at io.swagger.jaxrs.Reader$read.call(Unknown Source)
```

**Comment by webron** [comment]
It sounds to me like the bug is that `string` is assumed. It should actually fail if no type is mentioned. The goal of the annotation is to let you describe parameters on top of the types defined in the method, which means that you are required to provide all details.

**Comment by langecode** [comment]
Yeah, that could also be the case. Its just that the current stack trace is rather confusing - took a little debugging to figure out what was happening :-)

**Comment by webron** [comment]
Yeah, that's understandable. Can definitely be improved.
