### ISSUE TITLE
An exception trying to get a schema for inner classes.

### ISSUE THREAD

**Issue by lociko** [swagger-api/swagger-core#2620]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           |  Bug
| Which Swagger-Core version?       | 2.0.0-SNAPSHOT and 2.0.0-rc3
| Which Java version?               | Java 8
| Which JAX-RS framework & version? | any
 
Hi,
I'm basically having a problem getting the right model of my object. Actually, there is an exception :) 
My object looks like this:
```
@Schema(name = "TestObject", description = "TestObject description", oneOf = {
        TestObject.ChildTestObject.class,
        TestObject.Child2TestObject.class
})
public class TestObject {

    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    class ChildTestObject extends TestObject{
        private String childName;

        public String getChildName() {
            return childName;
        }

        public void setChildName(String childName) {
            this.childName = childName;
        }
    }

   class Child2TestObject extends TestObject{
        private String childName;

        public String getChildName() {
            return childName;
        }

        public void setChildName(String childName) {
            this.childName = childName;
        }
    }
}
```

As a result, a get the next exception:
```
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:744)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:742)
	at io.swagger.v3.core.jackson.ModelResolver.removeParentProperties(ModelResolver.java:996)
	at io.swagger.v3.core.jackson.ModelResolver.lambda$resolve$26(ModelResolver.java:529)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:525)
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:105)
	at io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:90)
	at io.swagger.v3.core.jackson.ModelResolver.lambda$resolve$26(ModelResolver.java:526)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:525)
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:105)
	at io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:90)
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:293)
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:105)
	at io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:90)
	at io.swagger.v3.core.jackson.ModelResolver.resolveProperty(ModelResolver.java:608)
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:96)
	at io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:112)
	at io.swagger.v3.core.jackson.ModelResolver.lambda$resolve$17(ModelResolver.java:406)
	at io.swagger.v3.core.jackson.ModelResolver.resolveAnnotatedType(ModelResolver.java:192)
	at io.swagger.v3.core.converter.ModelConverterContextImpl.resolveAnnotatedType(ModelConverterContextImpl.java:213)
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:400)
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:105)
	at io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:90)
	at io.swagger.v3.core.converter.ModelConverters.readAllAsResolvedSchema(ModelConverters.java:98)
	at io.swagger.v3.jaxrs2.OperationParser.getSchema(OperationParser.java:139)
	at io.swagger.v3.jaxrs2.OperationParser.getSchema(OperationParser.java:125)
	at io.swagger.v3.jaxrs2.OperationParser.getContent(OperationParser.java:92)
	at io.swagger.v3.jaxrs2.OperationParser.getApiResponses(OperationParser.java:60)
	at io.swagger.v3.jaxrs2.Reader.setOperationObjectFromApiOperationAnnotation(Reader.java:977)
	at io.swagger.v3.jaxrs2.Reader.parseMethod(Reader.java:800)
	at io.swagger.v3.jaxrs2.Reader.parseMethod(Reader.java:663)
	at io.swagger.v3.jaxrs2.Reader.read(Reader.java:391)
	at io.swagger.v3.jaxrs2.Reader.read(Reader.java:167)
	at io.swagger.v3.jaxrs2.Reader.read(Reader.java:194)
	at io.swagger.v3.oas.integration.GenericOpenApiContext.read(GenericOpenApiContext.java:349)
	at com.jaspersoft.ji.jaxrs.query.SwaggerDocumentationTest.testName(SwaggerDocumentationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
```

As a workaround, I can annotate my inner classes with @Shema annotation.

**Comment by lociko** [comment]
Can someone remove this bug, it is duplicate of https://github.com/swagger-api/swagger-core/issues/2619

**Comment by frantuma** [comment]
Closing as duplicate
