### ISSUE TITLE
Resolving schema loop

### ISSUE THREAD

**Issue by JohneDoe** [swagger-api/swagger-core#2774]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           | Bug
| Which Swagger-Core version?       | 2.0.2-SNAPSHOT
| Which Java version?               | 9
| Which JAX-RS framework & version? | -

Resolving Schema ends in loop, when Class of a Field is the same like the Class selfe.

```

@Data
@Builder
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class OrganisationUnitDTO {
  
  @Schema(nullable = true, title = "Child-Unit")
  private List<OrganisationUnitDTO> childs;

}
  
```

 ```
...
io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:90)
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:565)
	at io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:90)
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:366)
	at io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:90)
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:565)
	at io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:90)
	at io.swagger.v3.core.converter.ModelConverters.readAllAsResolvedSchema(ModelConverters.java:99)
	at io.swagger.v3.core.util.AnnotationsUtils.getSchema(AnnotationsUtils.java:1055)
	at io.swagger.v3.core.util.AnnotationsUtils.getSchema(AnnotationsUtils.java:1040)
	at io.swagger.v3.core.util.AnnotationsUtils.getContent(AnnotationsUtils.java:994)
	at io.swagger.v3.jaxrs2.OperationParser.getApiResponses(OperationParser.java:76)
	at io.swagger.v3.jaxrs2.Reader.setOperationObjectFromApiOperationAnnotation(Reader.java:1085)
	at io.swagger.v3.jaxrs2.Reader.parseMethod(Reader.java:885)
	at io.swagger.v3.jaxrs2.Reader.parseMethod(Reader.java:745)
	at io.swagger.v3.jaxrs2.Reader.read(Reader.java:422)
	at io.swagger.v3.jaxrs2.Reader.read(Reader.java:169)
```

**Comment by frantuma** [comment]
It's not clear which exception are you getting (StackOverflow?) and your full scenario, for which we would need some more details and a test case. This case should be handled ok (as e.g. in [this test](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/resources/MyThing.java)), possibly also see if that can be related to your lombok usage (try maybe be "delomboking" the class)

**Comment by MichakrawSB** [comment]
Closing this issue as part of our https://github.com/swagger-api/swagger-core/issues/5074.
This issue is outdated and/or inactive for a long time, and we’re not able to revisit it meaningfully.

If this problem is still relevant, please open a new issue and reference this one for context.
Thank you for your understanding!
