### ISSUE TITLE
swagger-gradle-plugin: ClassCastException on Task.Resolve in multiple subproject

### ISSUE THREAD

**Issue by mandopaloooza** [swagger-api/swagger-core#3134]
I am using swagger-gradle-plugin in multiple subprojects that correspond to different APIs. In each subproject, it generates the API documentation with Task.Resolve and then copies the documentation into the Tomcat staging directory. The documentations are consumed by a Swagger UI that is hosted within my web application. At the top-level gradle project, I have a task that depends on these tasks. 

Top-level project:
```
task stageSwagger {
    dependsOn { project('subproject-1').tasks.resolve }
    dependsOn { project('subproject-2').tasks.resolve }
    dependsOn { project('subproject-3').tasks.resolve }
}
```
Subproject:
```
resolve {
    outputFileName = "sample-openapi"
    classpath = getSwaggerClasspath()
    resourceClasses = getSwaggerResourceClasses()
    outputPath = buildDir.toPath()
}

task swagger(type: Copy) {
    dependsOn resolve
    from buildDir
    include 'sample-openapi.json'
    into tomcatStagingDir
}
```

When I run `task stageSwagger` from the top-level project, I am able to successfully execute subproject-1:resolve but any subsequent resolve tasks fail with the following exception: 

```
> Task :subproject-1:resolve
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

> Task :subproject-2:resolve FAILED
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':subproject-1:resolve'.
> org.gradle.api.GradleException (no error message)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':subproject-1:resolve'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:96)

...

Caused by: java.lang.reflect.InvocationTargetException
        at io.swagger.v3.plugins.gradle.tasks.ResolveTask.resolve(ResolveTask.java:388)
        ... 49 more
Caused by: java.lang.ExceptionInInitializerError
        at io.swagger.v3.jaxrs2.integration.JaxrsAnnotationScanner.classes(JaxrsAnnotationScanner.java:73)
        at io.swagger.v3.jaxrs2.integration.JaxrsApplicationAndAnnotationScanner.classes(JaxrsApplicationAndAnnotationScanner.java:10)
        at io.swagger.v3.oas.integration.GenericOpenApiContext.read(GenericOpenApiContext.java:469)
        at io.swagger.v3.jaxrs2.integration.SwaggerLoader.resolve(SwaggerLoader.java:215)
        ... 50 more
Caused by: java.lang.ClassCastException: com.sample.MyLogger cannot be cast to com.sample.MyLogger
        at com.sample.MyLogger.getLogger(MyLogger.java:61)
        at com.sample.MyClient.<clinit>(MyClient.java:64)
        ... 54 more
```

My guess for the above exception is that com.sample.MyLogger is loaded by a classloader but when the classes is casted, it is using com.sample.MyLogger from a different classloader, hence causing ClassCastException even if it's the same class. 

MyLogger.java is extended from java.util.logging.Logger. An instance of MyLogger is created by LogManager. Because LogManager can only return an instance of Logger, I have to cast MyLogger to the Logger object so the classes that uses it can access the methods in MyLogger. 
```
    public static MyLogger getLogger() {
        synchronized (Logger.class) {
            return (MyLogger) getLogger(className);
        }
    }

    public static Logger getLogger(String name) {
        synchronized (Logger.class) {
            LogManager manager = LogManager.getLogManager();
            Logger result = manager.getLogger(name);
            if (result == null) {
                result = new MyLogger(name);
                manager.addLogger(result);
                return manager.getLogger(name);
            }
            return result;
        }
    }
```

My question is:

Is it a bug in swagger-gradle-plugin that it tries to cast a class from a different classloader? 

OR 

Is there are different way that I can configure the gradle project such that the same classloader is used across different subprojects?

**Comment by michaeljohnstonverint** [comment]
ah, my exact issue. How did you work around this limitation ?

**Comment by MichakrawSB** [comment]
Closing this issue as part of our [housekeeping & cleanup](https://github.com/swagger-api/swagger-core/issues/5074).
This issue is outdated and/or inactive for a long time, and we’re not able to revisit it meaningfully.

If this problem is still relevant, please open a new issue and reference this one for context.
Thank you for your understanding!
