### ISSUE TITLE
io.swagger.jaxrs.config.BeanConfig.setScan throws refection issue

### ISSUE THREAD

**Issue by chenziliang** [swagger-api/swagger-core#3403]
Hi,

I encountered lots of reflection issue in `setScan` like below after upgrading `io.dropwizard` to 2.0. May you shed some lights to resolve this issue ? Thank you !

```
org.reflections.ReflectionsException: could not get type for name org.jboss.mx.util.JBossNotificationFilterSupport
    at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)            
    at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)           
    at org.reflections.Reflections.<init>(Reflections.java:126)                     
    at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:288)              
    at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:250)          
    at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:231)              
    at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:246)              
...
...             
    at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)         
    at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)           
    at io.dropwizard.cli.Cli.run(Cli.java:79)                                       
    at io.dropwizard.Application.run(Application.java:94) 
```

**Comment by chenziliang** [comment]
BTW, the io.swagger lib version is 1.6.0

**Comment by chenziliang** [comment]
After migration to 2.1.1, issue got resolved.
