### ISSUE TITLE
Getting org/apache/commons/lang/builder/ToStringStyle while using BeanConfig method setScan with parameter true

### ISSUE THREAD

**Issue by nitin065** [swagger-api/swagger-core#3516]
When using BeanConfig method setScan = true, getting following error:
`java.lang.NoClassDefFoundError: org/apache/commons/lang/builder/ToStringStyle
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3062)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2249)
	at com.fasterxml.jackson.databind.util.ClassUtil.getDeclaredFields(ClassUtil.java:1113)
	at com.fasterxml.jackson.databind.introspect.AnnotatedFieldCollector._findFields(AnnotatedFieldCollector.java:66)
	at com.fasterxml.jackson.databind.introspect.AnnotatedFieldCollector.collect(AnnotatedFieldCollector.java:41)
	at com.fasterxml.jackson.databind.introspect.AnnotatedFieldCollector.collectFields(AnnotatedFieldCollector.java:36)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClass._fields(AnnotatedClass.java:349)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClass.fields(AnnotatedClass.java:321)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:379)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:308)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:287)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:170)
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:164)
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:239)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:340)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:202)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:103)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:256)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:202)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:103)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:174)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:125)
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:83)
	at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:63)
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:905)
	at io.swagger.jaxrs.Reader.read(Reader.java:326)
	at io.swagger.jaxrs.Reader.read(Reader.java:176)
	at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:242)
	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:221)`

**Comment by MichakrawSB** [comment]
Closing this issue as part of our https://github.com/swagger-api/swagger-core/issues/5074.
This issue is outdated and/or inactive for a long time, and we’re not able to revisit it meaningfully.

If this problem is still relevant, please open a new issue and reference this one for context.
Thank you for your understanding!
