### ISSUE TITLE
Overriding Models data types not working

### ISSUE THREAD

**Issue by rartavia** [swagger-api/swagger-core#359]
I have a very simple model with a java.util.Calendar property, I want to present this as a simple string with date as a format (Similar to what we get with java.util.Date).

I tried what we have in the documentation https://github.com/wordnik/swagger-core/wiki/overriding-models#in-java-with-swagger-core-version-13x

... But it didn't work

My converter looks like this

```
public class Converter
{
  public void registerConverter()
  {
    String jsonString = "{" +
            "  \"id\": \"Calendar\"," +
            "  \"properties\": {" +
            "    \"value\": {" +
            "      \"required\": true," +
            "      \"description\": \"Date in ISO-8601 format\"," +
            "      \"notes\": \"Add any notes you like here\"," +
            "      \"type\": \"string\"," +
            "      \"format\": \"date-time\"" +
            "    }" +
            "  }" +
            "}";
    OverrideConverter converter = new OverrideConverter();
    converter.add("java.util.Calendar", jsonString);
  }
}
```

I'm initializing the converter using Spring, I wonder if that's sufficient and if it is, why is not working.

**Comment by cppexpert** [comment]
Guys, could you please tell me what I'm missing ? I want to override doc for one of my date classes because it's serialized to string. So I added

```java
            OverrideConverter converter = new OverrideConverter();
            String jsonString = "{" +
                    "  \"id\": \"TTLocalDate\"," +
                    "  \"properties\": {" +
                    "    \"value\": {" +
                    "      \"required\": true," +
                    "      \"description\": \"Date in ISO-8601 format\"," +
                    "      \"notes\": \"Add any notes you like here\"," +
                    "      \"type\": \"string\"," +
                    "      \"format\": \"date-time\"" +
                    "    }" +
                    "  }" +
                    "}";
            converter.add("com.crazyrabbit.date.TTLocalDate", jsonString);
            ModelConverters.addConverter(converter, true);
```

on startup I get exception which I can't even decypher

```
java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.hd$1()Ljava/lang/Object;
	at org.json4s.MonadicJValue.$bslash(MonadicJValue.scala:18)
	at com.wordnik.swagger.model.SwaggerSerializers$JsonSchemaModelSerializer$$anonfun$$init$$1$$anonfun$apply$1.applyOrElse(SwaggerSerializers.scala:37)
	at com.wordnik.swagger.model.SwaggerSerializers$JsonSchemaModelSerializer$$anonfun$$init$$1$$anonfun$apply$1.applyOrElse(SwaggerSerializers.scala:33)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:372)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:370)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at scala.collection.AbstractMap.applyOrElse(Map.scala:59)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.json4s.Extraction$.org$json4s$Extraction$$customOrElse(Extraction.scala:523)
	at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:512)
	at org.json4s.Extraction$.extract(Extraction.scala:351)
	at org.json4s.Extraction$.extract(Extraction.scala:42)
	at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
	at com.wordnik.swagger.converter.OverrideConverter.add(OverrideConverter.scala:33)
	at com.crazyrabbit.api2.SwaggerBootstrap.init(SwaggerBootstrap.java:30)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:595)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:385)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:862)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:300)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1341)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1334)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:744)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:497)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:186)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:498)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:146)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:605)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:528)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:391)
	at org.eclipse.jetty.util.Scanner$1.run(Scanner.java:329)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

```

**Comment by pradeepg-telsiz** [comment]
I am passing javax.json.JsonObject as a parameter. But each has different schema. How can I handle this? In UI, I can just see DataType as javax.json.JsonObject but I want to show proper schema. Can any  one please guide me?

**Comment by webron** [comment]
@pradeepg-telsiz - I'd suggest opening a new issue or rather send an email to the mailing list describing your use case.

**Comment by pradeepg-telsiz** [comment]
@webron Created issue. Issue number is 896.

**Comment by mfarhans** [comment]
The post was helpful and pointed me to the right direction...

Although, a quick question relating to Convertors, if someone can comment. When I define my convertor for "ZonedDateTime" for the properties "lastLogin" and "createdOn" properties (to String) using exactly the same pattern (as shown above for java.util.Calendar), the Swagger-UI response-model json schema-representation shows up like below:
{
  "id": "",
  "firstName": "",
  "lastName": "",
  "lastLogin": {
    "value": "date-time"
  },
  "createdOn": {
    "value": "date-time"
  }
}

The question I have is -- How can I avoid having the "value" sub-property in this json representation for the two ZonedDateTime fields. I am expecting the representation to be like below, is there something I am missing ?

{
  "id": "",
  "firstName": "",
  "lastName": "",
  "lastLogin": "",
  "createdOn": ""
}

**Comment by nikhilingole** [comment]
@mfarhans How did you solve this. Could you post a sample. 
I am facing a similar issue - https://groups.google.com/forum/#!topic/swagger-swaggersocket/Csa5lxcSg6w

**Comment by fehguy** [comment]
Hi @nikhilingole please reopen if the response in the google group doesn't help you solve your issue.
