### ISSUE TITLE
NullPointerException in io.swagger.v3.core.jackson.ModelResolver.getIgnoredProperties

### ISSUE THREAD

**Issue by tangjwtj** [swagger-api/swagger-core#3673]
io.swagger.v3.core.jackson.ModelResolver.getIgnoredProperties does not check jackson return value.
In getIgnoredProperties method,  assume jackson will not return null.

`Set<String> ignored = introspector.findPropertyIgnorals(beanDescription.getClassInfo()).findIgnoredForSerialization();`

But, In Jackson's implementation class AnnotationIntrospectorPair:

`    public Value findPropertyIgnorals(Annotated a) {
        Value v2 = this._secondary.findPropertyIgnorals(a);
        Value v1 = this._primary.findPropertyIgnorals(a);
        return v2 == null ? v1 : v2.withOverrides(v1);
    }`

v1/v2  may be null.

The exception:
java.lang.NullPointerException: null
	at io.swagger.v3.core.jackson.ModelResolver.getIgnoredProperties(ModelResolver.java:2002)
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:536)
	at org.springdoc.core.converters.AdditionalModelsConverter.resolve(AdditionalModelsConverter.java:100)
	at org.springdoc.core.converters.PropertyCustomizingConverter.resolve(PropertyCustomizingConverter.java:56)
	at org.springdoc.core.converters.FileSupportConverter.resolve(FileSupportConverter.java:50)
	at org.springdoc.core.converters.ResponseSupportConverter.resolve(ResponseSupportConverter.java:62)
	at org.springdoc.core.converters.SchemaPropertyDeprecatingConverter.resolve(SchemaPropertyDeprecatingConverter.java:55)
	at org.springdoc.core.converters.PolymorphicModelConverter.resolve(PolymorphicModelConverter.java:46)
	at io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:91)
	at io.swagger.v3.core.converter.ModelConverters.resolveAsResolvedSchema(ModelConverters.java:117)

**Comment by frantuma** [comment]
Thanks for reporting this, null check added in #3674
