### ISSUE TITLE
ClassCastException: javax.validation.constraints.Size

### ISSUE THREAD

**Issue by wickedsp1d3r** [swagger-api/swagger-core#3736]
Hey,
I am using Bean Validation constraint like this: `@Size(max = MY_CONSTANT, message = "{my-error}")`.
When trying to access Swagger, I get the following exception:
```
class com.sun.proxy.$Proxy140 cannot be cast to class javax.validation.constraints.Size (com.sun.proxy.$Proxy140 is in unnamed module of loader 'javax.validation.api' @2849defc; javax.validation.constraints.Size is in unnamed module of loader '<module>' @6160d8a5):
java.lang.ClassCastException: class com.sun.proxy.$Proxy140 cannot be cast to class javax.validation.constraints.Size (com.sun.proxy.$Proxy140 is in unnamed module of loader 'javax.validation.api' @2849defc; javax.validation.constraints.Size is in unnamed module of loader '<module>' @6160d8a5)
            at <module>//io.swagger.v3.core.jackson.ModelResolver.applyBeanValidatorAnnotations(ModelResolver.java:1164)
            at <module>//io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:700)
            at <module>//io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:90)
            at <module>//io.swagger.v3.core.converter.ModelConverters.readAllAsResolvedSchema(ModelConverters.java:99)
            at <module>//io.swagger.v3.core.util.AnnotationsUtils.getSchema(AnnotationsUtils.java:1125)
            at <module>//io.swagger.v3.core.util.AnnotationsUtils.getSchema(AnnotationsUtils.java:1110)
            at <module>//io.swagger.v3.core.util.AnnotationsUtils.getContent(AnnotationsUtils.java:1062)
            at <module>//io.swagger.v3.jaxrs2.OperationParser.getApiResponses(OperationParser.java:91)
            at <module>//io.swagger.v3.jaxrs2.Reader.parseMethod(Reader.java:965)
            at <module>//io.swagger.v3.jaxrs2.Reader.parseMethod(Reader.java:818)
            at <module>//io.swagger.v3.jaxrs2.Reader.read(Reader.java:450)
            at <module>//io.swagger.v3.jaxrs2.Reader.read(Reader.java:169)
            at <module>//io.swagger.v3.jaxrs2.Reader.read(Reader.java:196)
            at <module>//io.swagger.v3.oas.integration.GenericOpenApiContext.read(GenericOpenApiContext.java:463)
            at <module>//io.swagger.v3.jaxrs2.integration.resources.BaseOpenApiResource.getOpenApi(BaseOpenApiResource.java:49)
            at <module>//io.swagger.v3.jaxrs2.integration.resources.AcceptHeaderOpenApiResource.getOpenApiJson(AcceptHeaderOpenApiResource.java:30)
            at deployment.<deployment-name>.war//io.swagger.v3.jaxrs2.integration.resources.AcceptHeaderOpenApiResource$Proxy$_$$_WeldClientProxy.getOpenApiJson(Unknown Source)
            ...
```
I am using Swagger Core v2.1.1, but the issue is present also with the latest v2.1.5 version.

**Comment by amirzaman8088** [comment]
Hi. I experienced the same problem, how can i fix it ?

**Comment by zeusx-86** [comment]
hi, tell me how you solved this problem!?

**Comment by pedroramirezgft** [comment]
Hi, I fixed the problem by replacing all the javax.validantion.* imports by their corresponding jakarta.valitaion. I hope it helps you.

**Comment by karankumbhar47** [comment]
I facing same error, but javax.validataion.* imports being generated by openapi generator(which is not replaceable manually) how to handle this one?
