### ISSUE TITLE
JAXRS - No injection source found for a parameter of type public javax.ws.rs.core.Response

### ISSUE THREAD

**Issue by NeXT405** [swagger-api/swagger-core#3961]
Hi

I am facing a weird behaviour with OpenApi 3 and JAXRS. I dont no where to post this. Maybe it is a bug in jersey or a bug in swagger. 

I try to implement a file upload with the following definition from [this example](https://swagger.io/docs/specification/describing-request-body/multipart-requests/). I wrote the following yml as an example. 

```bash
java -jar ../swagger-codegen-cli-3.0.25.jar generate -i ../../clag/clag_test.yaml -l jaxrs-jersey -o ../../clag/generated_java
```

```yaml
openapi: 3.0.1
info:
  title: RESTful Routes 
  description: RESTful 
  contact:
    email: next405@example.com
  version: 1.0.0
servers:
- url: https://some.url.ch/test
tags:
- name: PublicAPI
paths:
  /v1/ping:
    get:
      tags:
      - PublicAPI
      summary: Healthcheck endpoint
      description: This endpoint provides an primitive healthcheck
      operationId: ping
      responses:
        204:
          description: Service is running and healthy, DB is connected
          content: {}
        500:
          description: Service is unhealthy
          content: {}
  /v1/userData/upload:
    post:
      tags:
      - PublicAPI
      summary: 'Upload a file'
      operationId: upload
      requestBody:
        required: true
        content:
          multipart/form-data: # Media type
            schema:            # Request payload
              type: object
              properties:      # Request parts
                id:            # Part 1 (string value)
                  type: string
                  format: uuid
                address:       # Part2 (object)
                  type: object
                  properties:
                    street:
                      type: string
                    city:
                      type: string
                profileImage:  # Part 3 (an image)
                  type: string
                  format: binary
      responses:
        200:
          description: |
            "Just a description"
```

This file generates a method like this: 

```java
@POST
@Path("/userData/upload")
@Consumes({ "multipart/form-data" })
@Operation(summary = "Upload a file", description = "", tags = { "PublicAPI" })
@ApiResponses(value = { @ApiResponse(responseCode = "200", description = "\"Just a description\"") })
public Response upload(
    @Parameter(description = "", required = true) @FormParam("id") UUID id,
    @Parameter(description = "", required = true) @FormParam("address") V1userDatauploadAddress address,
    @FormDataParam("profileImage") InputStream profileImageInputStream,
    @FormDataParam("profileImage") FormDataContentDisposition profileImageDetail,
    @Context SecurityContext securityContext) throws NotFoundException {
  return delegate.upload(id, address, profileImageInputStream, profileImageDetail, securityContext);
}
```

After starting the server with `clean package jetty:run` this exceptions gets thrown:

```
[[FATAL] No injection source found for a parameter of type public javax.ws.rs.core.Response io.swagger.api.V1Api.upload(java.util.UUID,io.swagger.model.V1userDatauploadAddress,java.io.InputStream,org.glassfish.jersey.media.multipart.FormDataContentDisposition,javax.ws.rs.core.SecurityContext) throws io.swagger.api.NotFoundException at index 1.; source='ResourceMethod{httpMethod=POST, consumedTypes=[multipart/form-data], producedTypes=[], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class io.swagger.api.V1Api, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@10f10230]}, definitionMethod=public javax.ws.rs.core.Response io.swagger.api.V1Api.upload(java.util.UUID,io.swagger.model.V1userDatauploadAddress,java.io.InputStream,org.glassfish.jersey.media.multipart.FormDataContentDisposition,javax.ws.rs.core.SecurityContext) throws io.swagger.api.NotFoundException, parameters=[Parameter [type=class java.util.UUID, source=id, defaultValue=null], Parameter [type=class io.swagger.model.V1userDatauploadAddress, source=address, defaultValue=null], Parameter [type=class java.io.InputStream, source=profileImage, defaultValue=null], Parameter [type=class org.glassfish.jersey.media.multipart.FormDataContentDisposition, source=profileImage, defaultValue=null], Parameter [type=interface javax.ws.rs.core.SecurityContext, source=null, defaultValue=null]], responseType=class javax.ws.rs.core.Response}, nameBindings=[]}']
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:394)
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:315)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:282)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:335)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:178)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:370)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612)
	... 51 more
```

With a lot of researching and testing I found out that every thing works when the object in the body gets replaces with just string values. 

```yaml
openapi: 3.0.1
info:
  title: RESTful Routes 
  description: RESTful 
  contact:
    email: mymail@example.com
  version: 1.0.0
servers:
- url: https://some.url.ch/test
tags:
- name: PublicAPI
paths:
  /v1/ping:
    get:
      tags:
      - PublicAPI
      summary: Healthcheck endpoint
      description: This endpoint provides an primitive healthcheck
      operationId: ping
      responses:
        204:
          description: Service is running and healthy, DB is connected
          content: {}
        500:
          description: Service is unhealthy
          content: {}
  /v1/userData/upload:
    post:
      tags:
      - PublicAPI
      summary: 'Upload a file'
      operationId: upload
      requestBody:
        required: true
        content:
          multipart/form-data: # Media type
            schema:            # Request payload
              type: object
              properties:      # Request parts
                id:            # Part 1 (string value)
                  type: string
                  format: uuid
                street:
                  type: string
                city:
                  type: string
                profileImage:  # Part 3 (an image)
                  type: string
                  format: binary
      responses:
        200:
          description: |
            "Just a description"
```

Produces:

```java
@POST
@Path("/userData/upload")
@Consumes({ "multipart/form-data" })
@Operation(summary = "Upload a file", description = "", tags = { "PublicAPI" })
@ApiResponses(value = { @ApiResponse(responseCode = "200", description = "\"Just a description\"") })
public Response upload(
    @Parameter(description = "", required = true) @FormParam("id") UUID id,
    @Parameter(description = "", required = true) @FormParam("street") String street,
    @Parameter(description = "", required = true) @FormParam("city") String city,
    @FormDataParam("profileImage") InputStream profileImageInputStream,
    @FormDataParam("profileImage") FormDataContentDisposition profileImageDetail,
    @Context SecurityContext securityContext) throws NotFoundException {
  return delegate.upload(id, street, city, profileImageInputStream, profileImageDetail, securityContext);
}
```

This works!

Do I miss something? Am I doing something wrong?

I think the problem is related to the https://github.com/swagger-api/swagger-core/issues/2567 and https://github.com/eclipse-ee4j/jersey/issues/3458. But in my case its not a problem of the order. When I replace `@Parameter(description = "", required = true) @FormParam("address") V1userDatauploadAddress address,` with `@Parameter(description = "", required = true) V1userDatauploadAddress address,` jetty can be started without a problem.

Any ideas? Any help is appreciated. :)

| Software          | Version         | 
| ---------------- |:---------------:| 
| Java                  | OracleJDK 8 191 | 
| Swagger code-gen | 3.0.25| 

Maven dependencies:

```
  <properties>
    <java.version>1.8</java.version>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
    <swagger-core-version>2.0.0</swagger-core-version>
    <jetty-version>9.2.9.v20150224</jetty-version>
    <jersey2-version>2.27</jersey2-version>
    <jackson-version>2.9.5</jackson-version>
    <junit-version>4.13.1</junit-version>
    <logback-version>1.1.7</logback-version>
    <servlet-api-version>2.5</servlet-api-version>
    <beanvalidation-version>1.1.0.Final</beanvalidation-version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
```
[example.zip](https://github.com/swagger-api/swagger-core/files/6564410/example.zip)

**Comment by MichakrawSB** [comment]
Closing this issue as part of our [housekeeping & cleanup](https://github.com/swagger-api/swagger-core/issues/5074).
This issue is outdated and/or inactive for a long time, and we’re not able to revisit it meaningfully.

If this problem is still relevant, please open a new issue and reference this one for context.
Thank you for your understanding!
