### ISSUE TITLE
MatchError when parsing Content-Type with charset

### ISSUE THREAD

**Issue by seratch** [swagger-api/swagger-core#428]
I just tried swagger-jersey-jaxrs with Jersey 1.18. Unfortunately I got a scala.MatchError.

``` xml
<dependency>
    <groupId>com.wordnik</groupId>
    <artifactId>swagger-jersey-jaxrs_2.10</artifactId>
    <version>1.3.0</version>
</dependency>
```

[prerequisite] We have a ContainerResponseFilter for specifying charset explicitly.

``` java
public class CharsetResponseFilter implements ContainerResponseFilter {
    @Override
    public ContainerResponse filter(ContainerRequest request, ContainerResponse response) {
        MediaType contentType = response.getMediaType();
        if (contentType == null) {
            response.getHttpHeaders().putSingle("Content-Type", "application/xml;charset=UTF-8");
        } else if (!contentType.toString().contains("charset=")) {
            response.getHttpHeaders().putSingle("Content-Type", contentType.toString() + ";charset=UTF-8");
        }
        return response;
    }
}
```

I just accessed to `/api-docs` and got scala.MatchError here.

https://github.com/wordnik/swagger-core/blob/swagger-project_2.10.0-1.3.0/modules/swagger-jaxrs/src/main/scala/com/wordnik/swagger/jaxrs/listing/SwaggerProviders.scala#L55

```
scala.MatchError: application/json; charset=UTF-8 (of class javax.ws.rs.core.MediaType)
    at com.wordnik.swagger.jaxrs.listing.ResourceListingProvider.writeTo(SwaggerProviders.scala:54)
    at com.wordnik.swagger.jaxrs.listing.ResourceListingProvider.writeTo(SwaggerProviders.scala:40)
```

**Comment by ron190** [comment]
I had the same `scala.MatchError` while using an old version of the library :
```
<dependency>
    <groupId>com.wordnik</groupId>
    <artifactId>swagger-jaxrs_2.10</artifactId>
    <version>1.3.1</version>
</dependency>
```
Changing to a new version has resolved the error :
```
<dependency>
    <groupId>com.wordnik</groupId>
    <artifactId>swagger-jaxrs_2.11</artifactId>
    <version>1.3.12</version>
</dependency>
```
