### ISSUE TITLE
java.lang.ClassCastException: class jdk.proxy2.$Proxy95 cannot be cast to class jakarta.validation.constraints.Min

### ISSUE THREAD

**Issue by siddhsql** [swagger-api/swagger-core#4656]
[MRE](https://github.com/swagger-api/swagger-core/files/14922879/openapi-mre.zip)

# Steps To Repro

1. unzip the MRE
2. mvn clean install
3. mvn spring-boot:run
4. navigate to http://localhost:8080/swagger-ui.html in browser

# Expected

Swagger UI

# Observed

```
SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.ClassCastException: class jdk.proxy2.$Proxy95 cannot be cast to class jakarta.validation.constraints.Min (jdk.proxy2.$Proxy95 is in module jdk.proxy2 of loader 'app'; jakarta.validation.constraints.Min is in unnamed module of loader 'app')] with root cause
java.lang.ClassCastException: class jdk.proxy2.$Proxy95 cannot be cast to class jakarta.validation.constraints.Min (jdk.proxy2.$Proxy95 is in module jdk.proxy2 of loader 'app'; jakarta.validation.constraints.Min is in unnamed module of loader 'app')
	at org.springdoc.core.service.AbstractRequestService.applyValidationsToSchema(AbstractRequestService.java:690)
	at org.springdoc.core.service.AbstractRequestService.applyBeanValidatorAnnotations(AbstractRequestService.java:587)
	at org.springdoc.core.service.AbstractRequestService.build(AbstractRequestService.java:338)
	at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:496)
	at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:676)
	at org.springdoc.webmvc.api.OpenApiResource.lambda$calculatePath$11(OpenApiResource.java:219)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.springdoc.webmvc.api.OpenApiResource.calculatePath(OpenApiResource.java:200)
	at org.springdoc.webmvc.api.OpenApiResource.lambda$getPaths$2(OpenApiResource.java:170)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.springdoc.webmvc.api.OpenApiResource.getPaths(OpenApiResource.java:149)
	at org.springdoc.api.AbstractOpenApiResource.getOpenApi(AbstractOpenApiResource.java:353)
	at org.springdoc.webmvc.api.OpenApiResource.openapiJson(OpenApiResource.java:124)
	at org.springdoc.webmvc.api.OpenApiWebMvcResource.openapiJson(OpenApiWebMvcResource.java:114)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
...
```

similar issue: https://github.com/swagger-api/swagger-core/issues/3736

how can I fix this? is this a bug or something wrong that I am doing?

**Comment by falseidol** [comment]
Hi, faced same problem, did you fixed it?

**Comment by andrei-galkin** [comment]
+1, still looking for a solution.

**Comment by sadmonsterr** [comment]
make sure that you use the Jarkata annotation

**Comment by frantuma** [comment]
Closing ticket as probably comment above by @sadmonsterr provides the solution. Please reopen if you're still experiencing issues
