### ISSUE TITLE
Swagger 2.0 If the return type is Response.Status Reader throws a NullPointer

### ISSUE THREAD

**Issue by arun0009** [swagger-api/swagger-core#877]
If the Resource return type is Response.Status Reader.java is throwing a NullPointerException 
	
Caused by: java.lang.NullPointerException
	at com.wordnik.swagger.jaxrs.Reader.isPrimitive(Reader.java:396) ~[swagger-jaxrs-1.5.1-M1.jar:1.5.1-M1]
	at com.wordnik.swagger.jaxrs.Reader.parseMethod(Reader.java:230) ~[swagger-jaxrs-1.5.1-M1.jar:1.5.1-M1]
	at com.wordnik.swagger.jaxrs.Reader.read(Reader.java:123) ~[swagger-jaxrs-1.5.1-M1.jar:1.5.1-M1]
	at com.wordnik.swagger.jaxrs.Reader.read(Reader.java:49) ~[swagger-jaxrs-1.5.1-M1.jar:1.5.1-M1]
	at com.wordnik.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:124) ~[swagger-jaxrs-1.5.1-M1.jar:1.5.1-M1]

**Comment by fehguy** [comment]
Thanks, this is a bug.  There's a quick fix to avoid the NPE but will take a bit longer to get the right response type given that Response.Status is an enum type and it should be exposed as an `integer`

**Comment by fehguy** [comment]
fixed in 1.5.2-M1-SNAPSHOT
