### ISSUE TITLE
java.lang.ClassNotFoundException: com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON

### ISSUE THREAD

**Issue by steowens** [swagger-api/swagger-core#880]
Even though I have verified that my pom file is pulling in: swagger-jaxrs_2.10-1.12.10.jar, and have verified the dependency in my maven dependencies.  Even though I have included an instantiation of the ApiListingResourceJSON in the constructor of one of my service classes in an attempt to force a compile error if the class loader is not in fact loading the class. When I start my application, I get the following error (listed below).  I suspect that there is a transitory dependency not getting picked up. 

```
lang.ClassNotFoundException: com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:730)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:196)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1045)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:949)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:295)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:292)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:626)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:389)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:294)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON] for bean with name 'swaggerResourceJSON' defined in ServletContext resource [/WEB-INF/servletContext.xml]; nested exception is java.lang.ClassNotFoundException: com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1275)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:575)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1344)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:356)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:335)
	at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:187)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:895)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:853)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:768)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:795)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:723)
	... 24 more
Caused by: java.lang.ClassNotFoundException: com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1702)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:260)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:416)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1296)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1267)
	... 34 more
```

**Comment by steowens** [comment]
Apparently it is partially working but it definately isn't working well.  Is scala something that could be screwing things up?

![screen shot 2015-02-19 at 12 50 38 pm](https://cloud.githubusercontent.com/assets/978310/6275690/096cfa10-b836-11e4-81ff-c60bee6259c4.png)

**Comment by steowens** [comment]
I have resolved the issue but you may want to update your documentation since it is easy to have happen.  The way this occurred is that I had a maven dependency on swagger-jaxrs_2.10, but I ALSO had a dependency on swagger-jaxrs-utils_2.1.   Removing the latter dependency fixed the issue.

**Comment by webron** [comment]
Where in the docs did you see you need to have swagger-jaxrs-utils_2.1 as a dependency?

**Comment by steowens** [comment]
I didn't but when you use eclipse to list swagger dependencies it comes up.  Like I said, it was user error but it is an easy error to have happen and a hard error to troubleshoot.

**Comment by fehguy** [comment]
Hi @steowens i don't think there is even a swagger-jaxrs_2.10-1.12.10 in existence?  You can see what you're trying to pull in by running mvn dependency:tree
