### ISSUE TITLE
Dropwizard Sample Doesn't Work?

### ISSUE THREAD

**Issue by arnm** [swagger-api/swagger-core#968]
I cloned the repo and tried to build and run the java-dropwizard sample app.

Down below is the error that I'm seeing.

I actually pulled down this sample app because I was having the same problem integrating the latest swagger (1.5.1-M2) into my existing dropwizard 7 app.

When I use swagger-jersey-jaxrs_2.11 1.3.12 it seems to work fine.

```
java -jar target/swagger-java-dropwizard-sample-app-1.5.1-M2.jar server conf/swagger-sample.yml
Picked up JAVA_TOOL_OPTIONS:  -Dfile.encoding=UTF-8 -Dfile.encoding=UTF-8
ERROR [2015-04-08 16:24:22,779] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: b617b2380c5c2c95
! java.lang.NullPointerException: null
! at com.wordnik.swagger.jaxrs.config.BeanConfig.configure(BeanConfig.java:223) ~[swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at com.wordnik.swagger.jaxrs.listing.ApiListingResource.scan(ApiListingResource.java:53) ~[swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at com.wordnik.swagger.jaxrs.listing.ApiListingResource.getListingJson(ApiListingResource.java:80) ~[swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_71]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_71]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_71]
! at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_71]
! at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at io.dropwizard.jersey.guava.OptionalResourceMethodDispatchAdapter$OptionalRequestDispatcher.dispatch(OptionalResourceMethodDispatchAdapter.java:37) ~[swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) ~[swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at com.sun.jersey.server.impl.uri.rules.ResourceObjectRule.accept(ResourceObjectRule.java:100) ~[swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:348) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:127) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:44) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:175) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:92) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:162) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.server.Server.handle(Server.java:446) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) [swagger-java-dropwizard-sample-app-1.5.1-M2.jar:1.5.1-M2]
! at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
```

**Comment by webron** [comment]
Fixed it in the develop_2.0 branch - https://github.com/swagger-api/swagger-core/commit/3185d08e6f72a60bf88fe711424cd3d7d6c1326d#diff-a4d244d88e30f7e9e8c99c041812f838.
