### ISSUE TITLE
Model does not match spec - causes code generators to fail

### ISSUE THREAD

**Issue by mjgp2** [swagger-api/swagger-core#974]
https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/com/wordnik/swagger/models/Response.java

```
Map<String,String> examples
```

According to [the spec for exampleObject](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#exampleObject) it should be `Map<String,Object>`

**Comment by webron** [comment]
While an `Object` may be a bit more accurate, `String` is not wrong or necessarily bad as it can contain the value as is. Since the spec defines it a `Any`, it also means the value can be a primitive on an array which can be represented by `Object` but I don't know if that's more useful than just using a string and deserializing if/as needed.

**Comment by mjgp2** [comment]
When reading my swagger it gives a json mapping exception because the value is a map not a string (content type => object). Can provide stack trace illater if you like?

**Comment by webron** [comment]
Sure, a stack trace would be great. The issue may be with the processing rather than the representation.

**Comment by mjgp2** [comment]
```
Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.wordnik.swagger.models.Swagger["paths"]->com.wordnik.swagger.models.Path["get"]->com.wordnik.swagger.models.Operation["responses"]->com.wordnik.swagger.models.Response["examples"])
reading from /home/mjgp2/import.io/api-docs/swagger-ui/swagger.json
Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.wordnik.swagger.models.Swagger["paths"]->com.wordnik.swagger.models.Path["get"]->com.wordnik.swagger.models.Operation["responses"]->com.wordnik.swagger.models.Response["examples"])
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:53)
	at com.wordnik.swagger.codegen.cmd.Generate.run(Generate.java:77)
	at com.wordnik.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:33)
```

from this [swagger](api.docs.import.io/swagger.json)

**Comment by webron** [comment]
@tomtit - are #988 / #1002 related?

**Comment by tomtit** [comment]
Yes they are, but [codegen](https://github.com/swagger-api/swagger-codegen)'s issue is [#646](https://github.com/swagger-api/swagger-codegen/issues/646) (PR [#676](https://github.com/swagger-api/swagger-codegen/pull/676)).

**Comment by webron** [comment]
Thanks, but in that case, this issue can be closed.
